
// Copyright 2012 Google Inc. All rights reserved.
(function(){

var data = {
"resource": {
  "version":"5",
  
  "macros":[{
      "function":"__e"
    },{
      "function":"__gas",
      "vtp_cookieDomain":"auto",
      "vtp_doubleClick":false,
      "vtp_setTrackerName":false,
      "vtp_useDebugVersion":false,
      "vtp_useHashAutoLink":false,
      "vtp_decorateFormsAutoLink":false,
      "vtp_enableLinkId":false,
      "vtp_enableEcommerce":false,
      "vtp_trackingId":"UA-52492337-2",
      "vtp_enableRecaptchaOption":false,
      "vtp_enableUaRlsa":false,
      "vtp_enableUseInternalVersion":false
    },{
      "function":"__gas",
      "vtp_cookieDomain":"auto",
      "vtp_doubleClick":false,
      "vtp_setTrackerName":false,
      "vtp_useDebugVersion":false,
      "vtp_useHashAutoLink":false,
      "vtp_decorateFormsAutoLink":false,
      "vtp_enableLinkId":false,
      "vtp_enableEcommerce":false,
      "vtp_trackingId":"UA-52492337-2",
      "vtp_enableRecaptchaOption":false,
      "vtp_enableUaRlsa":false,
      "vtp_enableUseInternalVersion":false
    },{
      "function":"__u",
      "vtp_component":"URL",
      "vtp_enableMultiQueryKeys":false,
      "vtp_enableIgnoreEmptyQueryParam":false
    },{
      "function":"__u",
      "vtp_component":"HOST",
      "vtp_enableMultiQueryKeys":false,
      "vtp_enableIgnoreEmptyQueryParam":false
    },{
      "function":"__u",
      "vtp_component":"PATH",
      "vtp_enableMultiQueryKeys":false,
      "vtp_enableIgnoreEmptyQueryParam":false
    },{
      "function":"__f",
      "vtp_component":"URL"
    },{
      "function":"__e"
    }],
  "tags":[{
      "function":"__ga",
      "metadata":["map"],
      "once_per_event":true,
      "vtp_detectTitle":true,
      "vtp_ignoredRef":["list"],
      "vtp_useDebugVersion":false,
      "vtp_allowLinker":false,
      "vtp_trackType":"TRACK_PAGEVIEW",
      "vtp_cookiePathCopy":["list"],
      "vtp_clientInfo":true,
      "vtp_campaignTrack":true,
      "vtp_anonymizeIp":false,
      "vtp_webPropertyId":"UA-52492337-2",
      "vtp_allowAnchor":false,
      "vtp_allowHash":true,
      "vtp_doubleClick":false,
      "vtp_setTrackerName":false,
      "vtp_sendHitsToGoogle":true,
      "vtp_enableInPageLinkId":false,
      "vtp_forceSsl":false,
      "vtp_ignoredOrganic":["list"],
      "vtp_detectFlash":true,
      "tag_id":1
    },{
      "function":"__ua",
      "metadata":["map"],
      "once_per_event":true,
      "vtp_overrideGaSettings":false,
      "vtp_trackType":"TRACK_PAGEVIEW",
      "vtp_gaSettings":["macro",1],
      "vtp_enableRecaptchaOption":false,
      "vtp_enableUaRlsa":false,
      "vtp_enableUseInternalVersion":false,
      "vtp_enableFirebaseCampaignData":true,
      "tag_id":2
    },{
      "function":"__hl",
      "tag_id":3
    }],
  "predicates":[{
      "function":"_eq",
      "arg0":["macro",0],
      "arg1":"gtm.historyChange"
    },{
      "function":"_eq",
      "arg0":["macro",0],
      "arg1":"gtm.js"
    }],
  "rules":[
    [["if",0],["add",0,1]],
    [["if",1],["add",2]]]
},
"runtime":[]




};


/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var aa,ba=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}},ca=function(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):{next:ba(a)}},da="function"==typeof Object.create?Object.create:function(a){var b=function(){};b.prototype=a;return new b},ea;
if("function"==typeof Object.setPrototypeOf)ea=Object.setPrototypeOf;else{var fa;a:{var ha={a:!0},ia={};try{ia.__proto__=ha;fa=ia.a;break a}catch(a){}fa=!1}ea=fa?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}
var ja=ea,la=function(a,b){a.prototype=da(b.prototype);a.prototype.constructor=a;if(ja)ja(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.Zi=b.prototype},na=this||self,pa=function(a){return a};var qa={},ra=function(a,b){qa[a]=qa[a]||[];qa[a][b]=!0},sa=function(a){for(var b=[],c=qa[a]||[],d=0;d<c.length;d++)c[d]&&(b[Math.floor(d/6)]^=1<<d%6);for(var e=0;e<b.length;e++)b[e]="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_".charAt(b[e]||0);return b.join("")};var ta=function(){},ua=function(a){return"function"==typeof a},va=function(a){return"string"==typeof a},wa=function(a){return"number"==typeof a&&!isNaN(a)},xa=function(a){var b="[object Array]"==Object.prototype.toString.call(Object(a));Array.isArray?Array.isArray(a)!==b&&ra("TAGGING",4):ra("TAGGING",5);return b},ya=function(a,b){if(Array.prototype.indexOf){var c=a.indexOf(b);return"number"==typeof c?c:-1}for(var d=0;d<a.length;d++)if(a[d]===b)return d;return-1},za=function(a,b){if(a&&xa(a))for(var c=
0;c<a.length;c++)if(a[c]&&b(a[c]))return a[c]},Aa=function(a,b){if(!wa(a)||!wa(b)||a>b)a=0,b=2147483647;return Math.floor(Math.random()*(b-a+1)+a)},Ea=function(a,b){for(var c=new Ca,d=0;d<a.length;d++)c.set(a[d],!0);for(var e=0;e<b.length;e++)if(c.get(b[e]))return!0;return!1},Ha=function(a,b){for(var c in a)Object.prototype.hasOwnProperty.call(a,c)&&b(c,a[c])},Ka=function(a){return!!a&&("[object Arguments]"==Object.prototype.toString.call(a)||Object.prototype.hasOwnProperty.call(a,"callee"))},La=
function(a){return Math.round(Number(a))||0},Ma=function(a){return"false"==String(a).toLowerCase()?!1:!!a},Na=function(a){var b=[];if(xa(a))for(var c=0;c<a.length;c++)b.push(String(a[c]));return b},Oa=function(a){return a?a.replace(/^\s+|\s+$/g,""):""},Pa=function(){return new Date(Date.now())},Ra=function(){return Pa().getTime()},Ca=function(){this.prefix="gtm.";this.values={}};Ca.prototype.set=function(a,b){this.values[this.prefix+a]=b};
Ca.prototype.get=function(a){return this.values[this.prefix+a]};
var Sa=function(a,b,c){return a&&a.hasOwnProperty(b)?a[b]:c},Va=function(a){var b=a;return function(){if(b){var c=b;b=void 0;try{c()}catch(d){}}}},Wa=function(a,b){for(var c in b)b.hasOwnProperty(c)&&(a[c]=b[c])},Xa=function(a){for(var b in a)if(a.hasOwnProperty(b))return!0;return!1},Ya=function(a,b){for(var c=[],d=0;d<a.length;d++)c.push(a[d]),c.push.apply(c,b[a[d]]||[]);return c},Za=function(a,b){for(var c={},d=c,e=a.split("."),f=0;f<e.length-1;f++)d=d[e[f]]={};d[e[e.length-1]]=b;return c},$a=/^\w{1,9}$/,
bb=function(a){var b=[];Ha(a,function(c,d){$a.test(c)&&d&&b.push(c)});return b.join(",")};var cb,db=function(){if(void 0===cb){var a=null,b=na.trustedTypes;if(b&&b.createPolicy){try{a=b.createPolicy("goog#html",{createHTML:pa,createScript:pa,createScriptURL:pa})}catch(c){na.console&&na.console.error(c.message)}cb=a}else cb=a}return cb};var fb=function(a,b){this.o=b===eb?a:""};fb.prototype.toString=function(){return this.o+""};var eb={};var gb=/^(?:(?:https?|mailto|ftp):|[^:/?#]*(?:[/?#]|$))/i;var hb;a:{var ib=na.navigator;if(ib){var kb=ib.userAgent;if(kb){hb=kb;break a}}hb=""}var lb=function(a){return-1!=hb.indexOf(a)};var nb=function(a,b,c){this.o=c===mb?a:""};nb.prototype.toString=function(){return this.o.toString()};var ob=function(a){return a instanceof nb&&a.constructor===nb?a.o:"type_error:SafeHtml"},mb={},pb=function(a){var b=db(),c=b?b.createHTML(a):a;return new nb(c,null,mb)},qb=new nb(na.trustedTypes&&na.trustedTypes.emptyHTML||"",0,mb);var rb=function(a,b){var c=function(){};c.prototype=a.prototype;var d=new c;a.apply(d,Array.prototype.slice.call(arguments,1));return d},sb=function(a){var b=a;return function(){if(b){var c=b;b=null;c()}}};var tb=function(a){var b=!1,c;return function(){b||(c=a(),b=!0);return c}}(function(){var a=document.createElement("div"),b=document.createElement("div");b.appendChild(document.createElement("div"));a.appendChild(b);var c=a.firstChild.firstChild;a.innerHTML=ob(qb);return!c.parentElement}),ub=function(a,b){if(tb())for(;a.lastChild;)a.removeChild(a.lastChild);a.innerHTML=ob(b)};var g=window,m=document,vb=navigator,wb=m.currentScript&&m.currentScript.src,xb=function(a,b){var c=g[a];g[a]=void 0===c?b:c;return g[a]},yb=function(a,b){b&&(a.addEventListener?a.onload=b:a.onreadystatechange=function(){a.readyState in{loaded:1,complete:1}&&(a.onreadystatechange=null,b())})},Bb=function(a,b,c){var d=m.createElement("script");d.type="text/javascript";d.async=!0;var e,f=db(),h=f?f.createScriptURL(a):a;e=new fb(h,eb);d.src=e instanceof fb&&e.constructor===fb?e.o:"type_error:TrustedResourceUrl";
var k,l,n=(d.ownerDocument&&d.ownerDocument.defaultView||window).document,p=null===(l=n.querySelector)||void 0===l?void 0:l.call(n,"script[nonce]");(k=p?p.nonce||p.getAttribute("nonce")||"":"")&&d.setAttribute("nonce",k);yb(d,b);c&&(d.onerror=c);var r=m.getElementsByTagName("script")[0]||m.body||m.head;r.parentNode.insertBefore(d,r);return d},Cb=function(){if(wb){var a=wb.toLowerCase();if(0===a.indexOf("https://"))return 2;if(0===a.indexOf("http://"))return 3}return 1},Db=function(a,b){var c=m.createElement("iframe");
c.height="0";c.width="0";c.style.display="none";c.style.visibility="hidden";var d=m.body&&m.body.lastChild||m.body||m.head;d.parentNode.insertBefore(c,d);yb(c,b);void 0!==a&&(c.src=a);return c},Eb=function(a,b,c){var d=new Image(1,1);d.onload=function(){d.onload=null;b&&b()};d.onerror=function(){d.onerror=null;c&&c()};d.src=a;return d},Fb=function(a,b,c,d){a.addEventListener?a.addEventListener(b,c,!!d):a.attachEvent&&a.attachEvent("on"+b,c)},Gb=function(a,b,c){a.removeEventListener?a.removeEventListener(b,
c,!1):a.detachEvent&&a.detachEvent("on"+b,c)},C=function(a){g.setTimeout(a,0)},Hb=function(a,b){return a&&b&&a.attributes&&a.attributes[b]?a.attributes[b].value:null},Ib=function(a){var b=a.innerText||a.textContent||"";b&&" "!=b&&(b=b.replace(/^[\s\xa0]+|[\s\xa0]+$/g,""));b&&(b=b.replace(/(\xa0+|\s{2,}|\n|\r\t)/g," "));return b},Jb=function(a){var b=m.createElement("div"),c=pb("A<div>"+a+"</div>");ub(b,c);b=b.lastChild;for(var d=[];b.firstChild;)d.push(b.removeChild(b.firstChild));return d},Kb=function(a,
b,c){c=c||100;for(var d={},e=0;e<b.length;e++)d[b[e]]=!0;for(var f=a,h=0;f&&h<=c;h++){if(d[String(f.tagName).toLowerCase()])return f;f=f.parentElement}return null},Qb=function(a){vb.sendBeacon&&vb.sendBeacon(a)||Eb(a)},Rb=function(a,b){var c=a[b];c&&"string"===typeof c.animVal&&(c=c.animVal);return c};/*
 jQuery v1.9.1 (c) 2005, 2012 jQuery Foundation, Inc. jquery.org/license. */
var Sb=/\[object (Boolean|Number|String|Function|Array|Date|RegExp)\]/,Tb=function(a){if(null==a)return String(a);var b=Sb.exec(Object.prototype.toString.call(Object(a)));return b?b[1].toLowerCase():"object"},Ub=function(a,b){return Object.prototype.hasOwnProperty.call(Object(a),b)},Vb=function(a){if(!a||"object"!=Tb(a)||a.nodeType||a==a.window)return!1;try{if(a.constructor&&!Ub(a,"constructor")&&!Ub(a.constructor.prototype,"isPrototypeOf"))return!1}catch(c){return!1}for(var b in a);return void 0===
b||Ub(a,b)},E=function(a,b){var c=b||("array"==Tb(a)?[]:{}),d;for(d in a)if(Ub(a,d)){var e=a[d];"array"==Tb(e)?("array"!=Tb(c[d])&&(c[d]=[]),c[d]=E(e,c[d])):Vb(e)?(Vb(c[d])||(c[d]={}),c[d]=E(e,c[d])):c[d]=e}return c};var Wb=function(a){if(void 0===a||xa(a)||Vb(a))return!0;switch(typeof a){case "boolean":case "number":case "string":case "function":return!0}return!1};var Xb=function(){var a=function(b){return{toString:function(){return b}}};return{xg:a("consent"),yg:a("consent_always_fire"),Oe:a("convert_case_to"),Pe:a("convert_false_to"),Qe:a("convert_null_to"),Re:a("convert_true_to"),Se:a("convert_undefined_to"),Ii:a("debug_mode_metadata"),kb:a("function"),jh:a("instance_name"),lh:a("live_only"),mh:a("malware_disabled"),nh:a("metadata"),Li:a("original_activity_id"),Mi:a("original_vendor_template_id"),ph:a("once_per_event"),uf:a("once_per_load"),Oi:a("priority_override"),
Pi:a("respected_consent_types"),yf:a("setup_tags"),zf:a("tag_id"),Af:a("teardown_tags")}}();var uc;
var vc=[],Bc=[],Cc=[],Dc=[],Ec=[],Fc={},Gc,Hc,Ic,Jc=function(a,b){var c=a["function"];if(!c)throw Error("Error: No function name given for function call.");var d=Fc[c],e={},f;for(f in a)if(a.hasOwnProperty(f))if(0===f.indexOf("vtp_"))d&&b&&b.Kf&&b.Kf(a[f]),e[void 0!==d?f:f.substr(4)]=a[f];else if(f===Xb.yg.toString()&&a[f]){}
d&&b&&b.Jf&&(e.vtp_gtmCachedValues=b.Jf);return void 0!==d?d(e):uc(c,e,b)},Lc=function(a,b,c){c=c||[];var d={},e;for(e in a)a.hasOwnProperty(e)&&(d[e]=Kc(a[e],b,c));return d},Kc=function(a,b,c){if(xa(a)){var d;switch(a[0]){case "function_id":return a[1];case "list":d=[];for(var e=1;e<a.length;e++)d.push(Kc(a[e],b,c));return d;case "macro":var f=a[1];if(c[f])return;var h=vc[f];if(!h||b.se(h))return;c[f]=!0;try{var k=Lc(h,b,c);k.vtp_gtmEventId=b.id;
d=Jc(k,b);Ic&&(d=Ic.Eh(d,k))}catch(y){b.Yf&&b.Yf(y,Number(f)),d=!1}c[f]=!1;return d;case "map":d={};for(var l=1;l<a.length;l+=2)d[Kc(a[l],b,c)]=Kc(a[l+1],b,c);return d;case "template":d=[];for(var n=!1,p=1;p<a.length;p++){var r=Kc(a[p],b,c);Hc&&(n=n||r===Hc.Qc);d.push(r)}return Hc&&n?Hc.Hh(d):d.join("");case "escape":d=Kc(a[1],b,c);if(Hc&&xa(a[1])&&"macro"===a[1][0]&&Hc.ai(a))return Hc.oi(d);d=String(d);for(var t=2;t<a.length;t++)Yb[a[t]]&&(d=Yb[a[t]](d));return d;case "tag":var q=a[1];if(!Dc[q])throw Error("Unable to resolve tag reference "+
q+".");return d={Rf:a[2],index:q};case "zb":var v={arg0:a[2],arg1:a[3],ignore_case:a[5]};v["function"]=a[1];var u=Mc(v,b,c),w=!!a[4];return w||2!==u?w!==(1===u):null;default:throw Error("Attempting to expand unknown Value type: "+a[0]+".");}}return a},Mc=function(a,b,c){try{return Gc(Lc(a,b,c))}catch(d){JSON.stringify(a)}return 2};var Pc=function(a){function b(t){for(var q=0;q<t.length;q++)d[t[q]]=!0}for(var c=[],d=[],e=Nc(a),f=0;f<Bc.length;f++){var h=Bc[f],k=Oc(h,e);if(k){for(var l=h.add||[],n=0;n<l.length;n++)c[l[n]]=!0;b(h.block||[])}else null===k&&b(h.block||[]);}for(var p=[],r=0;r<Dc.length;r++)c[r]&&!d[r]&&(p[r]=!0);return p},Oc=function(a,b){for(var c=a["if"]||[],d=0;d<c.length;d++){var e=b(c[d]);if(0===e)return!1;if(2===e)return null}for(var f=
a.unless||[],h=0;h<f.length;h++){var k=b(f[h]);if(2===k)return null;if(1===k)return!1}return!0},Nc=function(a){var b=[];return function(c){void 0===b[c]&&(b[c]=Mc(Cc[c],a));return b[c]}};var Qc={Eh:function(a,b){b[Xb.Oe]&&"string"===typeof a&&(a=1==b[Xb.Oe]?a.toLowerCase():a.toUpperCase());b.hasOwnProperty(Xb.Qe)&&null===a&&(a=b[Xb.Qe]);b.hasOwnProperty(Xb.Se)&&void 0===a&&(a=b[Xb.Se]);b.hasOwnProperty(Xb.Re)&&!0===a&&(a=b[Xb.Re]);b.hasOwnProperty(Xb.Pe)&&!1===a&&(a=b[Xb.Pe]);return a}};var H={Ub:"_ee",Wc:"_syn_or_mod",Qi:"_uei",Od:"_eu",Ni:"_pci",xb:"event_callback",Fc:"event_timeout",Ca:"gtag.config",Ka:"gtag.get",wa:"purchase",vb:"refund",Za:"begin_checkout",tb:"add_to_cart",ub:"remove_from_cart",Hg:"view_cart",Ue:"add_to_wishlist",Ja:"view_item",Ac:"view_promotion",zc:"select_promotion",td:"select_item",Lb:"view_item_list",Te:"add_payment_info",Gg:"add_shipping_info",Ua:"value_key",Ta:"value_callback",Da:"allow_ad_personalization_signals",Qb:"restricted_data_processing",Mb:"allow_google_signals",
Ga:"cookie_expires",Nb:"cookie_update",Sb:"session_duration",Kc:"session_engaged_time",Na:"user_properties",na:"transport_url",R:"ads_data_redaction",xa:"user_data",Ob:"first_party_collection",D:"ad_storage",H:"analytics_storage",Me:"region",Ne:"wait_for_update",Fa:"conversion_linker",Ea:"conversion_cookie_prefix",fa:"value",da:"currency",nf:"trip_type",X:"items",df:"passengers",ud:"allow_custom_scripts",Ab:"session_id",kf:"quantity",jb:"transaction_id",eb:"language",Ec:"country",Cc:"allow_enhanced_conversions",
zd:"aw_merchant_id",xd:"aw_feed_country",yd:"aw_feed_language",wd:"discount",Ye:"developer_id",Mc:"delivery_postal_code",Fd:"estimated_delivery_date",Dd:"shipping",Md:"new_customer",Ad:"customer_lifetime_value",Ed:"enhanced_conversions",wb:"page_view",ma:"linker",N:"domains",hb:"decorate_forms"};H.rf=[H.wa,H.vb,H.Za,H.tb,H.ub,H.Hg,H.Ue,H.Ja,H.Ac,H.zc,H.Lb,H.td,H.Te,H.Gg];H.qf=[H.Da,H.Mb,H.Nb];H.sf=[H.Ga,H.Fc,H.Sb,H.Kc];var td=function(a){ra("GTM",a)};var ud=function(a,b){this.o=a;this.defaultValue=void 0===b?!1:b};var vd=new ud(1936,!0),wd=new ud(1933);var yd=function(){var a=xd;if(a.pe&&a.hasOwnProperty("pe"))return a.pe;var b=new a;return a.pe=b};var xd=function(){var a={};this.o=function(b,c){return null!=a[b]?a[b]:c};this.s=function(){a[wd.o]=!0}},Dd=function(a){return yd().o(a.o,a.defaultValue)};var Ed=[];function Fd(){var a=xb("google_tag_data",{});a.ics||(a.ics={entries:{},set:Gd,update:Hd,addListener:Id,notifyListeners:Jd,active:!1,usedDefault:!1});return a.ics}
function Gd(a,b,c,d,e,f){var h=Fd();h.active=!0;h.usedDefault=!0;if(void 0!=b){var k=h.entries,l=k[a]||{},n=l.region,p=c&&va(c)?c.toUpperCase():void 0;d=d.toUpperCase();e=e.toUpperCase();if(""===d||p===e||(p===d?n!==e:!p&&!n)){var r=!!(f&&0<f&&void 0===l.update),t={region:p,initial:"granted"===b,update:l.update,quiet:r};if(""!==d||!1!==l.initial)k[a]=t;r&&g.setTimeout(function(){k[a]===t&&t.quiet&&(t.quiet=!1,Kd(a),Jd(),ra("TAGGING",2))},f)}}}
function Hd(a,b){var c=Fd();c.active=!0;if(void 0!=b){var d=Ld(a),e=c.entries,f=e[a]=e[a]||{};f.update="granted"===b;var h=Ld(a);f.quiet?(f.quiet=!1,Kd(a)):h!==d&&Kd(a)}}function Id(a,b){Ed.push({ee:a,Ph:b})}function Kd(a){for(var b=0;b<Ed.length;++b){var c=Ed[b];xa(c.ee)&&-1!==c.ee.indexOf(a)&&(c.ag=!0)}}function Jd(a){for(var b=0;b<Ed.length;++b){var c=Ed[b];if(c.ag){c.ag=!1;try{c.Ph({Dh:a})}catch(d){}}}}
var Ld=function(a){var b=Fd().entries[a]||{};return void 0!==b.update?b.update:b.initial},Md=function(a){return(Fd().entries[a]||{}).initial},Nd=function(a){return!(Fd().entries[a]||{}).quiet},Od=function(){return Dd(wd)?Fd().active:!1},Pd=function(){return Fd().usedDefault},Qd=function(a,b){Fd().addListener(a,b)},Rd=function(a){Fd().notifyListeners(a)},Sd=function(a,b){function c(){for(var e=0;e<b.length;e++)if(!Nd(b[e]))return!0;return!1}if(c()){var d=!1;Qd(b,function(e){d||c()||(d=!0,a(e))})}else a({})},
Td=function(a,b){function c(){for(var f=[],h=0;h<d.length;h++){var k=d[h];!1===Ld(k)||e[k]||(f.push(k),e[k]=!0)}return f}var d=va(b)?[b]:b,e={};c().length!==d.length&&Qd(d,function(f){var h=c();0<h.length&&(f.ee=h,a(f))})};function Ud(a){for(var b=[],c=0;c<Vd.length;c++){var d=a(Vd[c]);b[c]=!0===d?"1":!1===d?"0":"-"}return b.join("")}
var Vd=[H.D,H.H],Wd=function(a){var b=a[H.Me];b&&td(40);var c=a[H.Ne];c&&td(41);for(var d=xa(b)?b:[b],e={Hb:0};e.Hb<d.length;e={Hb:e.Hb},++e.Hb)Ha(a,function(f){return function(h,k){if(h!==H.Me&&h!==H.Ne){var l=d[f.Hb];Fd().set(h,k,l,"IN","",c)}}}(e))},Xd=function(a,b){Ha(a,function(c,d){Fd().update(c,d)});Rd(b)},K=function(a){var b=Ld(a);return void 0!=b?b:!0},Yd=function(){return"G1"+Ud(Ld)},Zd=function(a,b){Td(a,b)},$d=function(a,b){Sd(a,b)};var be=function(a){return ae?m.querySelectorAll(a):null},ce=function(a,b){if(!ae)return null;if(Element.prototype.closest)try{return a.closest(b)}catch(e){return null}var c=Element.prototype.matches||Element.prototype.webkitMatchesSelector||Element.prototype.mozMatchesSelector||Element.prototype.msMatchesSelector||Element.prototype.oMatchesSelector,d=a;if(!m.documentElement.contains(d))return null;do{try{if(c.call(d,b))return d}catch(e){break}d=d.parentElement||d.parentNode}while(null!==d&&1===d.nodeType);
return null},de=!1;if(m.querySelectorAll)try{var ee=m.querySelectorAll(":root");ee&&1==ee.length&&ee[0]==m.documentElement&&(de=!0)}catch(a){}var ae=de;var fe,ge=!1;var he=function(a){if(m.hidden)return!0;var b=a.getBoundingClientRect();if(b.top==b.bottom||b.left==b.right||!g.getComputedStyle)return!0;var c=g.getComputedStyle(a,null);if("hidden"===c.visibility)return!0;for(var d=a,e=c;d;){if("none"===e.display)return!0;var f=e.opacity,h=e.filter;if(h){var k=h.indexOf("opacity(");0<=k&&(h=h.substring(k+8,h.indexOf(")",k)),"%"==h.charAt(h.length-1)&&(h=h.substring(0,h.length-1)),f=Math.min(h,f))}if(void 0!==f&&0>=f)return!0;(d=d.parentElement)&&(e=g.getComputedStyle(d,
null))}return!1};var qe=/:[0-9]+$/,re=function(a,b,c){for(var d=a.split("&"),e=0;e<d.length;e++){var f=d[e].split("=");if(decodeURIComponent(f[0]).replace(/\+/g," ")===b){var h=f.slice(1).join("=");return c?h:decodeURIComponent(h).replace(/\+/g," ")}}},ue=function(a,b,c,d,e){b&&(b=String(b).toLowerCase());if("protocol"===b||"port"===b)a.protocol=se(a.protocol)||se(g.location.protocol);"port"===b?a.port=String(Number(a.hostname?a.port:g.location.port)||("http"==a.protocol?80:"https"==a.protocol?443:"")):"host"===b&&
(a.hostname=(a.hostname||g.location.hostname).replace(qe,"").toLowerCase());return te(a,b,c,d,e)},te=function(a,b,c,d,e){var f,h=se(a.protocol);b&&(b=String(b).toLowerCase());switch(b){case "url_no_fragment":f=ve(a);break;case "protocol":f=h;break;case "host":f=a.hostname.replace(qe,"").toLowerCase();if(c){var k=/^www\d*\./.exec(f);k&&k[0]&&(f=f.substr(k[0].length))}break;case "port":f=String(Number(a.port)||("http"==h?80:"https"==h?443:""));break;case "path":a.pathname||a.hostname||ra("TAGGING",
1);f="/"==a.pathname.substr(0,1)?a.pathname:"/"+a.pathname;var l=f.split("/");0<=ya(d||[],l[l.length-1])&&(l[l.length-1]="");f=l.join("/");break;case "query":f=a.search.replace("?","");e&&(f=re(f,e,void 0));break;case "extension":var n=a.pathname.split(".");f=1<n.length?n[n.length-1]:"";f=f.split("/")[0];break;case "fragment":f=a.hash.replace("#","");break;default:f=a&&a.href}return f},se=function(a){return a?a.replace(":","").toLowerCase():""},ve=function(a){var b="";if(a&&a.href){var c=a.href.indexOf("#");
b=0>c?a.href:a.href.substr(0,c)}return b},we=function(a){var b=m.createElement("a");a&&(b.href=a);var c=b.pathname;"/"!==c[0]&&(a||ra("TAGGING",1),c="/"+c);var d=b.hostname.replace(qe,"");return{href:b.href,protocol:b.protocol,host:b.host,hostname:d,pathname:c,search:b.search,hash:b.hash,port:b.port}},xe=function(a){function b(n){var p=n.split("=")[0];return 0>d.indexOf(p)?n:p+"=0"}function c(n){return n.split("&").map(b).filter(function(p){return void 0!=p}).join("&")}var d="gclid dclid gbraid wbraid gclaw gcldc gclha gclgf gclgb _gl".split(" "),
e=we(a),f=a.split(/[?#]/)[0],h=e.search,k=e.hash;"?"===h[0]&&(h=h.substring(1));"#"===k[0]&&(k=k.substring(1));h=c(h);k=c(k);""!==h&&(h="?"+h);""!==k&&(k="#"+k);var l=""+f+h+k;"/"===l[l.length-1]&&(l=l.substring(0,l.length-1));return l};var ye={},ze=!0;var Be=new RegExp(/[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}/i),Ce=new RegExp(/@(gmail|googlemail)\./i),Ie=new RegExp(/support|noreply/i),Je="SCRIPT STYLE IMG SVG PATH BR".split(" "),Ke=["BR"],Le={};
function Me(a){var b;if(a===m.body)b="body";else{var c;if(a.id)c="#"+a.id;else{var d;if(a.parentElement){var e;a:{var f=a.parentElement;if(f){for(var h=0;h<f.childElementCount;h++)if(f.children[h]===a){e=h+1;break a}e=-1}else e=1}d=Me(a.parentElement)+">:nth-child("+e+")"}else d="";c=d}b=c}return b}function Ne(a,b){if(1>=a.length)return a;var c=a.filter(b);return 0==c.length?a:c}
function Oe(a){if(0==a.length)return null;var b;b=Ne(a,function(c){return!Ie.test(c.va)});b=Ne(b,function(c){return"INPUT"===c.element.tagName.toUpperCase()});b=Ne(b,function(c){return!he(c.element)});return b[0]}
var Pe=function(a){var b=!a||!!a.Xh,c=!a||!!a.Yh,d=b+"."+c;a&&a.cd&&a.cd.length&&(d+="."+a.cd.join("."));var e=Le[d];if(e&&200>Ra()-e.timestamp)return e.result;var f;var h=[],k=m.body;if(k){for(var l=k.querySelectorAll("*"),n=0;n<l.length&&1E4>n;n++){var p=l[n];if(!(0<=Je.indexOf(p.tagName.toUpperCase()))){for(var r=!1,t=0;t<p.childElementCount&&1E4>t;t++)if(!(0<=Ke.indexOf(p.children[t].tagName.toUpperCase()))){r=!0;break}r||h.push(p)}}f={elements:h,status:1E4<l.length?"2":"1"}}else f={elements:h,
status:"4"};for(var q=f,v=q.elements,u=[],w=0;w<v.length;w++){var y=v[w],x=y.textContent;y.value&&(x=y.value);if(x){var z=x.match(Be);if(z){var A=z[0],B;if(g.location){var D=te(g.location,"host",!0);B=0<=A.toLowerCase().indexOf(D)}else B=!1;B||u.push({element:y,va:A})}}}var F;var G=a&&a.cd;if(G&&0!==G.length){for(var J=[],N=0;N<u.length;N++){for(var S=!0,R=0;R<G.length;R++){var P=G[R];if(P&&ce(u[N].element,P)){S=!1;break}}S&&J.push(u[N])}F=J}else F=u;var I=Oe(F),Q=[];if(I){var U=I.element,M={va:I.va,
tagName:U.tagName,type:1};b&&(M.querySelector=Me(U));c&&(M.isVisible=!he(U));Q.push(M)}var Y={elements:Q,status:10<u.length?"3":q.status};Le[d]={timestamp:Ra(),result:Y};return Y},Qe=function(a){return a.tagName+":"+a.isVisible+":"+a.va.length+":"+Ce.test(a.va)};
var Re=function(a){return/^e\d+$/.test(a)||/^[0-9A-Za-z_-]{43}$/.test(a)},Se=function(a){return void 0===a||null===a?"":va(a)?Oa(String(a)):"e0"},Ue=function(a){return a.replace(Te,"")},We=function(a){return Ve(a.replace(/\s/g,""))},Ve=function(a){return Oa(a.replace(Xe,"").toLowerCase())},Ze=function(a){a=a.replace(/[\s-()/.]/g,"");"+"!==a.charAt(0)&&(a="+"+a);return Ye.test(a)?a:"e0"},af=function(a){var b=a.toLowerCase().split("@");if(2==b.length){var c=b[0];/^(gmail|googlemail)\./.test(b[1])&&
(c=c.replace(/\./g,""));c=c+"@"+b[1];if($e.test(c))return c}return"e0"},df=function(a,b,c){window.Promise||c([],[]);Promise.all(a.map(function(d){return d.value&&bf(d.name)?cf(d.value).then(function(e){d.value=e}):Promise.resolve()})).then(function(){c(a,b)}).catch(function(){c([],[])})},cf=function(a){if(""===a||"e0"===a)return Promise.resolve(a);if(g.crypto&&g.crypto.subtle)try{var b=ef(a);return g.crypto.subtle.digest("SHA-256",b).then(function(c){var d=Array.from(new Uint8Array(c)).map(function(e){return String.fromCharCode(e)}).join("");
return g.btoa(d).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/,"")}).catch(function(){return"e2"})}catch(c){return Promise.resolve("e2")}else return Promise.resolve("e1")},ef=function(a){var b;if(g.TextEncoder)b=(new g.TextEncoder("utf-8")).encode(a);else{for(var c=[],d=0;d<a.length;d++){var e=a.charCodeAt(d);128>e?c.push(e):2048>e?c.push(192|e>>6,128|e&63):55296>e||57344<=e?c.push(224|e>>12,128|e>>6&63,128|e&63):(e=65536+((e&1023)<<10|a.charCodeAt(++d)&1023),c.push(240|e>>18,128|e>>12&63,128|
e>>6&63,128|e&63))}b=new Uint8Array(c)}return b},Xe=/[0-9`~!@#$%^&*()_\-+=:;<>,.?|/\\[\]]/g,$e=/^\S+@\S+\.\S+$/,Ye=/^\+\d{11,15}$/,Te=/[.~]/g,ff={},gf=(ff.email="em",ff.phone_number="pn",ff.first_name="fn",ff.last_name="ln",ff.street="sa",ff.city="ct",ff.region="rg",ff.country="co",ff.postal_code="pc",ff.error_code="ec",ff),hf=function(a,b,c){function d(v,u,w){var y=v[u];xa(y)||(y=[y]);for(var x=0;x<y.length;++x){var z=Se(y[x]);""!==z&&h.push({name:u,value:w(z),index:void 0})}}function e(v,u,w,y){var x=
Se(v[u]);""!==x&&h.push({name:u,value:w(x),index:y})}function f(v){return function(u){td(64);return v(u)}}var h=[],k=[];if("https:"===g.location.protocol){d(a,"email",af);d(a,"phone_number",Ze);d(a,"first_name",f(We));d(a,"last_name",f(We));var r=a.home_address||{};d(r,"street",f(Ve));d(r,"city",f(Ve));d(r,"postal_code",f(Ue));d(r,"region",f(Ve));d(r,"country",f(Ue));var t=a.address||{};xa(t)||(t=[t]);for(var q=0;q<t.length;q++)e(t[q],"first_name",We,q),e(t[q],"last_name",We,q),e(t[q],"street",Ve,q),e(t[q],"city",Ve,q),e(t[q],"postal_code",Ue,
q),e(t[q],"region",Ve,q),e(t[q],"country",Ue,q);df(h,k,c)}else h.push({name:"error_code",value:"e3",index:void 0}),c(h,k)},jf=function(a,b){hf(a,[],function(c,d){for(var e=["tv.1"],f=0;f<c.length;++f){var h=c[f].name,k=c[f].value,l=c[f].index,n=gf[h];n&&k&&(!bf(h)||Re(k))&&(void 0!==l&&(n+=l),e.push(n+"."+k))}b(encodeURIComponent(e.join("~")),d)})},kf=function(a,b){if(g.Promise)try{return new Promise(function(c){hf(a,b,function(d,e){for(var f=["tv.1"],h=0;h<d.length;++h){var k=d[h].name,l=d[h].value,
n=d[h].index,p=gf[k];p&&l&&(!bf(k)||Re(l))&&(void 0!==n&&(p+=n),f.push(p+"."+l))}c({mc:encodeURIComponent(f.join("~")),$b:e})})})}catch(c){}},bf=function(a){return-1!==["email","phone_number","first_name","last_name","street"].indexOf(a)};var lf={},mf=null,nf=Math.random();lf.M="GTM-526RRG4";lf.Vc="7c0";lf.Ki="";lf.Ag="ChEI8Ja6hwYQxYKF+IS0vKyIARIkANXoO5nIxiaXxIpiHHf00y2FKrrnXnaXDQV0xAdWbqXfPNuEGgIn0g\x3d\x3d";var of={__cl:!0,__ecl:!0,__ehl:!0,__evl:!0,__fal:!0,__fil:!0,__fsl:!0,__hl:!0,__jel:!0,__lcl:!0,__sdl:!0,__tl:!0,__ytl:!0},pf={__paused:!0,__tg:!0},qf;for(qf in of)of.hasOwnProperty(qf)&&(pf[qf]=!0);var rf="www.googletagmanager.com/gtm.js";
var sf=rf,tf=Ma(""),uf=null,vf=null,wf="https://www.googletagmanager.com/a?id="+lf.M+"&cv=5",xf={},yf={},zf=function(){var a=mf.sequence||1;mf.sequence=a+1;return a};lf.zg="";var Af={},Bf=new Ca,Cf={},Df={},Gf={name:"dataLayer",set:function(a,b){E(Za(a,b),Cf);Ef()},get:function(a){return Ff(a,2)},reset:function(){Bf=new Ca;Cf={};Ef()}},Ff=function(a,b){return 2!=b?Bf.get(a):Hf(a)},Hf=function(a){var b,c=a.split(".");b=b||[];for(var d=Cf,e=0;e<c.length;e++){if(null===d)return!1;if(void 0===d)break;d=d[c[e]];if(-1!==ya(b,d))return}return d},If=function(a,b){Df.hasOwnProperty(a)||(Bf.set(a,b),E(Za(a,b),Cf),Ef())},Ef=function(a){Ha(Df,function(b,c){Bf.set(b,c);E(Za(b,
void 0),Cf);E(Za(b,c),Cf);a&&delete Df[b]})},Kf=function(a,b,c){Af[a]=Af[a]||{};Af[a][b]=Jf(b,c)},Jf=function(a,b){var c,d=1!==(void 0===b?2:b)?Hf(a):Bf.get(a);"array"===Tb(d)||"object"===Tb(d)?c=E(d):c=d;return c},Lf=function(a,b){if(Af[a])return Af[a][b]},Mf=function(a,b){Af[a]&&delete Af[a][b]};
var Nf=function(a,b,c){if(c){var d=c.selector_type,e=String(c.value),f;if("js_variable"===d)if(e=e.replace(/\["?'?/g,".").replace(/"?'?\]/g,""),0===e.indexOf("dataLayer."))f=Ff(e.substring(10));else{var h=e.split(".");f=g[h.shift()];for(var k=0;k<h.length;k++)f=f&&f[h[k]]}else if("css_selector"===d&&ae){var l=be(e);l&&0<l.length&&(f=Ib(l[0])||Oa(l[0].value))}f&&(a[b]=f)}},Of=function(a){if(a){var b={};Nf(b,"email",a.email);Nf(b,"phone_number",a.phone);b.address=[];for(var c=a.name_and_address||[],
d=0;d<c.length;d++){var e={};Nf(e,"first_name",c[d].first_name);Nf(e,"last_name",c[d].last_name);Nf(e,"street",c[d].street);Nf(e,"city",c[d].city);Nf(e,"region",c[d].region);Nf(e,"country",c[d].country);Nf(e,"postal_code",c[d].postal_code);b.address.push(e)}return b}},Pf=function(a){if(a)switch(a.mode){case "selectors":return Of(a.selectors);case "auto_detect":var b=a.auto_detect,c=Pe({Xh:!1,Yh:!1,cd:b&&b.exclude_element_selectors}).elements,d={};if(0<c.length)for(var e=0;e<c.length;e++){var f=c[e];
if(1===f.type){d.email=f.va;break}}return d}},Qf=function(a){switch(a.enhanced_conversions_mode){case "manual":var b=a.enhanced_conversions_manual_var;return void 0!==b?b:g.enhanced_conversion_data;case "automatic":return Of(a.enhanced_conversions_automatic_settings)}};var Rf={},Sf=function(a,b){if(g._gtmexpgrp&&g._gtmexpgrp.hasOwnProperty(a))return g._gtmexpgrp[a];void 0===Rf[a]&&(Rf[a]=Math.floor(Math.random()*b));return Rf[a]};function Tf(a,b,c){for(var d=[],e=b.split(";"),f=0;f<e.length;f++){var h=e[f].split("="),k=h[0].replace(/^\s*|\s*$/g,"");if(k&&k==a){var l=h.slice(1).join("=").replace(/^\s*|\s*$/g,"");l&&c&&(l=decodeURIComponent(l));d.push(l)}}return d};function Uf(a){return"null"!==a.origin};var Xf=function(a,b,c,d){return Vf(d)?Tf(a,String(b||Wf()),c):[]},$f=function(a,b,c,d,e){if(Vf(e)){var f=Yf(a,d,e);if(1===f.length)return f[0].id;if(0!==f.length){f=Zf(f,function(h){return h.bd},b);if(1===f.length)return f[0].id;f=Zf(f,function(h){return h.nc},c);return f[0]?f[0].id:void 0}}};function ag(a,b,c,d){var e=Wf(),f=window;Uf(f)&&(f.document.cookie=a);var h=Wf();return e!=h||void 0!=c&&0<=Xf(b,h,!1,d).indexOf(c)}
var eg=function(a,b,c){function d(q,v,u){if(null==u)return delete h[v],q;h[v]=u;return q+"; "+v+"="+u}function e(q,v){if(null==v)return delete h[v],q;h[v]=!0;return q+"; "+v}if(!Vf(c.Qa))return 2;var f;void 0==b?f=a+"=deleted; expires="+(new Date(0)).toUTCString():(c.encode&&(b=encodeURIComponent(b)),b=bg(b),f=a+"="+b);var h={};f=d(f,"path",c.path);var k;c.expires instanceof Date?k=c.expires.toUTCString():null!=c.expires&&(k=""+c.expires);f=d(f,"expires",k);f=d(f,"max-age",c.Wi);f=d(f,"samesite",
c.Xi);c.Yi&&(f=e(f,"secure"));var l=c.domain;if("auto"===l){for(var n=cg(),p=0;p<n.length;++p){var r="none"!==n[p]?n[p]:void 0,t=d(f,"domain",r);t=e(t,c.flags);if(!dg(r,c.path)&&ag(t,a,b,c.Qa))return 0}return 1}l&&"none"!==l&&(f=d(f,"domain",l));f=e(f,c.flags);return dg(l,c.path)?1:ag(f,a,b,c.Qa)?0:1},fg=function(a,b,c){null==c.path&&(c.path="/");c.domain||(c.domain="auto");return eg(a,b,c)};
function Zf(a,b,c){for(var d=[],e=[],f,h=0;h<a.length;h++){var k=a[h],l=b(k);l===c?d.push(k):void 0===f||l<f?(e=[k],f=l):l===f&&e.push(k)}return 0<d.length?d:e}function Yf(a,b,c){for(var d=[],e=Xf(a,void 0,void 0,c),f=0;f<e.length;f++){var h=e[f].split("."),k=h.shift();if(!b||-1!==b.indexOf(k)){var l=h.shift();l&&(l=l.split("-"),d.push({id:h.join("."),bd:1*l[0]||1,nc:1*l[1]||1}))}}return d}
var bg=function(a){a&&1200<a.length&&(a=a.substring(0,1200));return a},gg=/^(www\.)?google(\.com?)?(\.[a-z]{2})?$/,hg=/(^|\.)doubleclick\.net$/i,dg=function(a,b){return hg.test(window.document.location.hostname)||"/"===b&&gg.test(a)},Wf=function(){return Uf(window)?window.document.cookie:""},cg=function(){var a=[],b=window.document.location.hostname.split(".");if(4===b.length){var c=b[b.length-1];if(parseInt(c,10).toString()===c)return["none"]}for(var d=b.length-2;0<=d;d--)a.push(b.slice(d).join("."));
var e=window.document.location.hostname;hg.test(e)||gg.test(e)||a.push("none");return a},Vf=function(a){if(!Dd(wd)||!a||!Od())return!0;if(!Nd(a))return!1;var b=Ld(a);return null==b?!0:!!b};var ig=function(){return[Math.round(2147483647*Math.random()),Math.round(Ra()/1E3)].join(".")},lg=function(a,b,c,d,e){var f=jg(b);return $f(a,f,kg(c),d,e)},qg=function(a,b,c,d){var e=""+jg(c),f=kg(d);1<f&&(e+="-"+f);return[b,e,a].join(".")},jg=function(a){if(!a)return 1;a=0===a.indexOf(".")?a.substr(1):a;return a.split(".").length},kg=function(a){if(!a||"/"===a)return 1;"/"!==a[0]&&(a="/"+a);"/"!==a[a.length-1]&&(a+="/");return a.split("/").length-1};function rg(a,b,c){var d,e=Number(null!=a.nb?a.nb:void 0);0!==e&&(d=new Date((b||Ra())+1E3*(e||7776E3)));return{path:a.path,domain:a.domain,flags:a.flags,encode:!!c,expires:d}};var sg=["1"],tg={},xg=function(a){var b=ug(a.prefix);if(!tg[b]&&!vg(b,a.path,a.domain)){var c=ig();if(0===wg(b,c,a)){var d=xb("google_tag_data",{});d._gcl_au?ra("GTM",57):d._gcl_au=c}vg(b,a.path,a.domain)}};function wg(a,b,c){var d=qg(b,"1",c.domain,c.path),e=rg(c);e.Qa="ad_storage";return fg(a,d,e)}function vg(a,b,c){var d=lg(a,b,c,sg,"ad_storage");d&&(tg[a]=d);return d}function ug(a){return(a||"_gcl")+"_au"};var yg=function(a){for(var b=[],c=m.cookie.split(";"),d=new RegExp("^\\s*"+(a||"_gac")+"_(UA-\\d+-\\d+)=\\s*(.+?)\\s*$"),e=0;e<c.length;e++){var f=c[e].match(d);f&&b.push({He:f[1],value:f[2],timestamp:Number(f[2].split(".")[1])||0})}b.sort(function(h,k){return k.timestamp-h.timestamp});return b};
function zg(a,b){var c=yg(a),d={};if(!c||!c.length)return d;for(var e=0;e<c.length;e++){var f=c[e].value.split(".");if(!("1"!==f[0]||b&&3>f.length||!b&&3!==f.length)&&Number(f[1])){d[c[e].He]||(d[c[e].He]=[]);var h={version:f[0],timestamp:1E3*Number(f[1]),Aa:f[2]};b&&3<f.length&&(h.labels=f.slice(3));d[c[e].He].push(h)}}return d};function Ag(){for(var a=Bg,b={},c=0;c<a.length;++c)b[a[c]]=c;return b}function Cg(){var a="ABCDEFGHIJKLMNOPQRSTUVWXYZ";a+=a.toLowerCase()+"0123456789-_";return a+"."}var Bg,Dg;
function Eg(a){function b(l){for(;d<a.length;){var n=a.charAt(d++),p=Dg[n];if(null!=p)return p;if(!/^[\s\xa0]*$/.test(n))throw Error("Unknown base64 encoding at char: "+n);}return l}Bg=Bg||Cg();Dg=Dg||Ag();for(var c="",d=0;;){var e=b(-1),f=b(0),h=b(64),k=b(64);if(64===k&&-1===e)return c;c+=String.fromCharCode(e<<2|f>>4);64!=h&&(c+=String.fromCharCode(f<<4&240|h>>2),64!=k&&(c+=String.fromCharCode(h<<6&192|k)))}};var Fg;var Jg=function(){var a=Gg,b=Hg,c=Ig(),d=function(h){a(h.target||h.srcElement||{})},e=function(h){b(h.target||h.srcElement||{})};if(!c.init){Fb(m,"mousedown",d);Fb(m,"keyup",d);Fb(m,"submit",e);var f=HTMLFormElement.prototype.submit;HTMLFormElement.prototype.submit=function(){b(this);f.call(this)};c.init=!0}},Kg=function(a,b,c,d,e){var f={callback:a,domains:b,fragment:2===c,placement:c,forms:d,sameHost:e};Ig().decorators.push(f)},Lg=function(a,b,c){for(var d=Ig().decorators,e={},f=0;f<d.length;++f){var h=
d[f],k;if(k=!c||h.forms)a:{var l=h.domains,n=a,p=!!h.sameHost;if(l&&(p||n!==m.location.hostname))for(var r=0;r<l.length;r++)if(l[r]instanceof RegExp){if(l[r].test(n)){k=!0;break a}}else if(0<=n.indexOf(l[r])||p&&0<=l[r].indexOf(n)){k=!0;break a}k=!1}if(k){var t=h.placement;void 0==t&&(t=h.fragment?2:1);t===b&&Wa(e,h.callback())}}return e},Ig=function(){var a=xb("google_tag_data",{}),b=a.gl;b&&b.decorators||(b={decorators:[]},a.gl=b);return b};var Mg=/(.*?)\*(.*?)\*(.*)/,Ng=/^https?:\/\/([^\/]*?)\.?cdn\.ampproject\.org\/?(.*)/,Og=/^(?:www\.|m\.|amp\.)+/,Pg=/([^?#]+)(\?[^#]*)?(#.*)?/;function Qg(a){return new RegExp("(.*?)(^|&)"+a+"=([^&]*)&?(.*)")}
var Sg=function(a){var b=[],c;for(c in a)if(a.hasOwnProperty(c)){var d=a[c];if(void 0!==d&&d===d&&null!==d&&"[object Object]"!==d.toString()){b.push(c);var e=b,f=e.push,h,k=String(d);Bg=Bg||Cg();Dg=Dg||Ag();for(var l=[],n=0;n<k.length;n+=3){var p=n+1<k.length,r=n+2<k.length,t=k.charCodeAt(n),q=p?k.charCodeAt(n+1):0,v=r?k.charCodeAt(n+2):0,u=t>>2,w=(t&3)<<4|q>>4,y=(q&15)<<2|v>>6,x=v&63;r||(x=64,p||(y=64));l.push(Bg[u],Bg[w],Bg[y],Bg[x])}h=l.join("");f.call(e,h)}}var z=b.join("*");return["1",Rg(z),
z].join("*")},Rg=function(a,b){var c=[window.navigator.userAgent,(new Date).getTimezoneOffset(),window.navigator.userLanguage||window.navigator.language,Math.floor((new Date).getTime()/60/1E3)-(void 0===b?0:b),a].join("*"),d;if(!(d=Fg)){for(var e=Array(256),f=0;256>f;f++){for(var h=f,k=0;8>k;k++)h=h&1?h>>>1^3988292384:h>>>1;e[f]=h}d=e}Fg=d;for(var l=4294967295,n=0;n<c.length;n++)l=l>>>8^Fg[(l^c.charCodeAt(n))&255];return((l^-1)>>>0).toString(36)},Ug=function(){return function(a){var b=we(g.location.href),
c=b.search.replace("?",""),d=re(c,"_gl",!0)||"";a.query=Tg(d)||{};var e=ue(b,"fragment").match(Qg("_gl"));a.fragment=Tg(e&&e[3]||"")||{}}},Vg=function(a){var b=Ug(),c=Ig();c.data||(c.data={query:{},fragment:{}},b(c.data));var d={},e=c.data;e&&(Wa(d,e.query),a&&Wa(d,e.fragment));return d},Tg=function(a){var b;b=void 0===b?3:b;try{if(a){var c;a:{for(var d=a,e=0;3>e;++e){var f=Mg.exec(d);if(f){c=f;break a}d=decodeURIComponent(d)}c=void 0}var h=c;if(h&&"1"===h[1]){var k=h[3],l;a:{for(var n=h[2],p=0;p<
b;++p)if(n===Rg(k,p)){l=!0;break a}l=!1}if(l){for(var r={},t=k?k.split("*"):[],q=0;q<t.length;q+=2)r[t[q]]=Eg(t[q+1]);return r}}}}catch(v){}};function Wg(a,b,c,d){function e(p){var r=p,t=Qg(a).exec(r),q=r;if(t){var v=t[2],u=t[4];q=t[1];u&&(q=q+v+u)}p=q;var w=p.charAt(p.length-1);p&&"&"!==w&&(p+="&");return p+n}d=void 0===d?!1:d;var f=Pg.exec(c);if(!f)return"";var h=f[1],k=f[2]||"",l=f[3]||"",n=a+"="+b;d?l="#"+e(l.substring(1)):k="?"+e(k.substring(1));return""+h+k+l}
function Xg(a,b){var c="FORM"===(a.tagName||"").toUpperCase(),d=Lg(b,1,c),e=Lg(b,2,c),f=Lg(b,3,c);if(Xa(d)){var h=Sg(d);c?Yg("_gl",h,a):Zg("_gl",h,a,!1)}if(!c&&Xa(e)){var k=Sg(e);Zg("_gl",k,a,!0)}for(var l in f)if(f.hasOwnProperty(l))a:{var n=l,p=f[l],r=a;if(r.tagName){if("a"===r.tagName.toLowerCase()){Zg(n,p,r,void 0);break a}if("form"===r.tagName.toLowerCase()){Yg(n,p,r);break a}}"string"==typeof r&&Wg(n,p,r,void 0)}}
function Zg(a,b,c,d){if(c.href){var e=Wg(a,b,c.href,void 0===d?!1:d);gb.test(e)&&(c.href=e)}}
function Yg(a,b,c){if(c&&c.action){var d=(c.method||"").toLowerCase();if("get"===d){for(var e=c.childNodes||[],f=!1,h=0;h<e.length;h++){var k=e[h];if(k.name===a){k.setAttribute("value",b);f=!0;break}}if(!f){var l=m.createElement("input");l.setAttribute("type","hidden");l.setAttribute("name",a);l.setAttribute("value",b);c.appendChild(l)}}else if("post"===d){var n=Wg(a,b,c.action);gb.test(n)&&(c.action=n)}}}
var Gg=function(a){try{var b;a:{for(var c=a,d=100;c&&0<d;){if(c.href&&c.nodeName.match(/^a(?:rea)?$/i)){b=c;break a}c=c.parentNode;d--}b=null}var e=b;if(e){var f=e.protocol;"http:"!==f&&"https:"!==f||Xg(e,e.hostname)}}catch(h){}},Hg=function(a){try{if(a.action){var b=ue(we(a.action),"host");Xg(a,b)}}catch(c){}},$g=function(a,b,c,d){Jg();Kg(a,b,"fragment"===c?2:1,!!d,!1)},ah=function(a,b){Jg();Kg(a,[te(g.location,"host",!0)],b,!0,!0)},bh=function(){var a=m.location.hostname,b=Ng.exec(m.referrer);if(!b)return!1;
var c=b[2],d=b[1],e="";if(c){var f=c.split("/"),h=f[1];e="s"===h?decodeURIComponent(f[2]):decodeURIComponent(h)}else if(d){if(0===d.indexOf("xn--"))return!1;e=d.replace(/-/g,".").replace(/\.\./g,"-")}var k=a.replace(Og,""),l=e.replace(Og,""),n;if(!(n=k===l)){var p="."+l;n=k.substring(k.length-p.length,k.length)===p}return n},ch=function(a,b){return!1===a?!1:a||b||bh()};var dh={};var eh=/^\w+$/,fh=/^[\w-]+$/,gh={aw:"_aw",dc:"_dc",gf:"_gf",ha:"_ha",gp:"_gp",gb:"_gb"},hh=function(){if(!Dd(wd)||!Od())return!0;var a=Ld("ad_storage");return null==a?!0:!!a},ih=function(a,b){Nd("ad_storage")?hh()?a():Td(a,"ad_storage"):b?ra("TAGGING",3):Sd(function(){ih(a,!0)},["ad_storage"])},kh=function(a){return jh(a).map(function(b){return b.Aa})},jh=function(a){var b=[];if(!Uf(g)||!m.cookie)return b;var c=Xf(a,m.cookie,void 0,"ad_storage");if(!c||0==c.length)return b;for(var d={},e=0;e<c.length;d=
{wc:d.wc},e++){var f=lh(c[e]);if(null!=f){var h=f,k=h.version;d.wc=h.Aa;var l=h.timestamp,n=h.labels,p=za(b,function(r){return function(t){return t.Aa===r.wc}}(d));p?(p.timestamp=Math.max(p.timestamp,l),p.labels=mh(p.labels,n||[])):b.push({version:k,Aa:d.wc,timestamp:l,labels:n})}}b.sort(function(r,t){return t.timestamp-r.timestamp});return nh(b)};function mh(a,b){for(var c={},d=[],e=0;e<a.length;e++)c[a[e]]=!0,d.push(a[e]);for(var f=0;f<b.length;f++)c[b[f]]||d.push(b[f]);return d}
function oh(a){return a&&"string"==typeof a&&a.match(eh)?a:"_gcl"}
var qh=function(){var a=we(g.location.href),b=ue(a,"query",!1,void 0,"gclid"),c=ue(a,"query",!1,void 0,"gclsrc"),d=ue(a,"query",!1,void 0,"wbraid"),e=ue(a,"query",!1,void 0,"dclid");if(!b||!c||!d){var f=a.hash.replace("#","");b=b||re(f,"gclid",void 0);c=c||re(f,"gclsrc",void 0);d=d||re(f,"wbraid",void 0)}return ph(b,c,e,d)},ph=function(a,b,c,d){var e={},f=function(h,k){e[k]||(e[k]=[]);e[k].push(h)};e.gclid=a;e.gclsrc=b;e.dclid=c;void 0!==d&&fh.test(d)&&(e.gbraid=d,f(d,"gb"));if(void 0!==a&&a.match(fh))switch(b){case void 0:f(a,
"aw");break;case "aw.ds":f(a,"aw");f(a,"dc");break;case "ds":f(a,"dc");break;case "3p.ds":f(a,"dc");break;case "gf":f(a,"gf");break;case "ha":f(a,"ha")}c&&f(c,"dc");return e},rh=function(a,b){switch(a){case void 0:case "aw":return"aw"===b;case "aw.ds":return"aw"===b||"dc"===b;case "ds":case "3p.ds":return"dc"===b;case "gf":return"gf"===b;case "ha":return"ha"===b}return!1},th=function(a){var b=qh();ih(function(){sh(b,a)})};
function sh(a,b,c,d){function e(p,r){var t=uh(p,f);t&&(fg(t,r,h),k=!0)}b=b||{};d=d||[];var f=oh(b.prefix);c=c||Ra();var h=rg(b,c,!0);h.Qa="ad_storage";var k=!1,l=Math.round(c/1E3),n=function(p){var r=["GCL",l,p];0<d.length&&r.push(d.join("."));return r.join(".")};a.aw&&e("aw",n(a.aw[0]));a.dc&&e("dc",n(a.dc[0]));a.gf&&e("gf",n(a.gf[0]));a.ha&&e("ha",n(a.ha[0]));a.gp&&e("gp",n(a.gp[0]));(void 0==dh.enable_gbraid_cookie_write?0:dh.enable_gbraid_cookie_write)&&!k&&a.gb&&e("gb",n(a.gb[0]))}
var wh=function(a,b){var c=Vg(!0);ih(function(){for(var d=oh(b.prefix),e=0;e<a.length;++e){var f=a[e];if(void 0!==gh[f]){var h=uh(f,d),k=c[h];if(k){var l=Math.min(vh(k),Ra()),n;b:{var p=l;if(Uf(g))for(var r=Xf(h,m.cookie,void 0,"ad_storage"),t=0;t<r.length;++t)if(vh(r[t])>p){n=!0;break b}n=!1}if(!n){var q=rg(b,l,!0);q.Qa="ad_storage";fg(h,k,q)}}}}sh(ph(c.gclid,c.gclsrc),b)})},uh=function(a,b){var c=gh[a];if(void 0!==c)return b+c},vh=function(a){return 0!==xh(a.split(".")).length?1E3*(Number(a.split(".")[1])||
0):0};function lh(a){var b=xh(a.split("."));return 0===b.length?null:{version:b[0],Aa:b[2],timestamp:1E3*(Number(b[1])||0),labels:b.slice(3)}}function xh(a){return 3>a.length||"GCL"!==a[0]&&"1"!==a[0]||!/^\d+$/.test(a[1])||!fh.test(a[2])?[]:a}
var yh=function(a,b,c,d,e){if(xa(b)&&Uf(g)){var f=oh(e),h=function(){for(var k={},l=0;l<a.length;++l){var n=uh(a[l],f);if(n){var p=Xf(n,m.cookie,void 0,"ad_storage");p.length&&(k[n]=p.sort()[p.length-1])}}return k};ih(function(){$g(h,b,c,d)})}},nh=function(a){return a.filter(function(b){return fh.test(b.Aa)})},zh=function(a,b){if(Uf(g)){for(var c=oh(b.prefix),d={},e=0;e<a.length;e++)gh[a[e]]&&(d[a[e]]=gh[a[e]]);ih(function(){Ha(d,function(f,h){var k=Xf(c+h,m.cookie,void 0,"ad_storage");k.sort(function(q,
v){return vh(v)-vh(q)});if(k.length){var l=k[0],n=vh(l),p=0!==xh(l.split(".")).length?l.split(".").slice(3):[],r={},t;t=0!==xh(l.split(".")).length?l.split(".")[2]:void 0;r[f]=[t];sh(r,b,n,p)}})})}};function Ah(a,b){for(var c=0;c<b.length;++c)if(a[b[c]])return!0;return!1}
var Bh=function(a){function b(e,f,h){h&&(e[f]=h)}if(Od()){var c=qh();if(Ah(c,a)){var d={};b(d,"gclid",c.gclid);b(d,"dclid",c.dclid);b(d,"gclsrc",c.gclsrc);b(d,"wbraid",c.gbraid);ah(function(){return d},3);ah(function(){var e={};return e._up="1",e},1)}}};function Ch(a,b){var c=oh(b),d=uh(a,c);if(!d)return 0;for(var e=jh(d),f=0,h=0;h<e.length;h++)f=Math.max(f,e[h].timestamp);return f}
function Dh(a){var b=0,c;for(c in a)for(var d=a[c],e=0;e<d.length;e++)b=Math.max(b,Number(d[e].timestamp));return b};var Eh=/^\d+\.fls\.doubleclick\.net$/;function Fh(a,b){Nd(H.D)?K(H.D)?a():Td(a,H.D):b?td(42):$d(function(){Fh(a,!0)},[H.D])}function Gh(a){var b=we(g.location.href),c=ue(b,"host",!1);if(c&&c.match(Eh)){var d=ue(b,"path").split(a+"=");if(1<d.length)return d[1].split(";")[0].split("?")[0]}}
function Hh(a,b,c){if("aw"===a||"dc"===a||"gb"===a){var d=Gh("gcl"+a);if(d)return d.split(".")}var e=oh(b);if("_gcl"==e){c=void 0===c?!0:c;var f=!K(H.D)&&c,h;h=qh()[a]||[];if(0<h.length)return f?["0"]:h}var k=uh(a,e);return k?kh(k):[]}function Ih(a){var b=[];Ha(a,function(c,d){d=nh(d);for(var e=[],f=0;f<d.length;f++)e.push(d[f].Aa);e.length&&b.push(c+":"+e.join(","))});return b.join(";")}
var Jh=function(a){var b=Gh("gac");return b?!K(H.D)&&a?"0":decodeURIComponent(b):Ih(hh()?zg():{})},Kh=function(a){var b=Gh("gacgb");return b?!K(H.D)&&a?"0":decodeURIComponent(b):Ih(hh()?zg("_gac_gb",!0):{})},Lh=function(a,b,c){var d=qh(),e=[],f=d.gclid,h=d.dclid,k=d.gclsrc||"aw";!f||"aw.ds"!==k&&"aw"!==k&&"ds"!==k||c&&!rh(k,c)||e.push({Aa:f,je:k});!h||c&&"dc"!==c||e.push({Aa:h,je:"ds"});Fh(function(){xg(b);var l=tg[ug(b.prefix)],n=!1;if(l&&0<e.length)for(var p=mf.joined_auid=mf.joined_auid||{},r=0;r<e.length;r++){var t=e[r],q=t.Aa,v=t.je,u=(b.prefix||"_gcl")+"."+v+"."+q;if(!p[u]){var w="https://adservice.google.com/pagead/regclk";w="gb"===v?w+"?gbraid="+q+"&auid="+l:w+"?gclid="+q+"&auid="+l+"&gclsrc="+v;Qb(w);n=p[u]=!0}}null==a&&(a=n);
if(a&&l){var y=ug(b.prefix),x=tg[y];x&&wg(y,x,b)}})},Mh=function(a){var b;if(Gh("gclaw")||Gh("gac")||0<(qh().aw||[]).length)b=!1;else{var c;if(0<(qh().gb||[]).length)c=!0;else{var d=Math.max(Ch("aw",a),Dh(hh()?zg():{}));c=Math.max(Ch("gb",a),Dh(hh()?zg("_gac_gb",!0):{}))>d}b=c}return b};var Nh=/[A-Z]+/,Oh=/\s/,Ph=function(a){if(va(a)&&(a=Oa(a),!Oh.test(a))){var b=a.indexOf("-");if(!(0>b)){var c=a.substring(0,b);if(Nh.test(c)){for(var d=a.substring(b+1).split("/"),e=0;e<d.length;e++)if(!d[e])return;return{id:a,prefix:c,containerId:c+"-"+d[0],O:d}}}}},Rh=function(a){for(var b={},c=0;c<a.length;++c){var d=Ph(a[c]);d&&(b[d.id]=d)}Qh(b);var e=[];Ha(b,function(f,h){e.push(h)});return e};
function Qh(a){var b=[],c;for(c in a)if(a.hasOwnProperty(c)){var d=a[c];"AW"===d.prefix&&d.O[1]&&b.push(d.containerId)}for(var e=0;e<b.length;++e)delete a[b[e]]};var Sh=function(){var a=!1;return a};var Uh=function(a,b,c,d){return(2===Th()||d||"http:"!=g.location.protocol?a:b)+c},Th=function(){var a=Cb(),b;if(1===a)a:{var c=sf;c=c.toLowerCase();for(var d="https://"+c,e="http://"+c,f=1,h=m.getElementsByTagName("script"),k=0;k<h.length&&100>k;k++){var l=h[k].src;if(l){l=l.toLowerCase();if(0===l.indexOf(e)){b=3;break a}1===f&&0===l.indexOf(d)&&(f=2)}}b=f}else b=a;return b};var fi=function(a,b){var c=a?Qf(a):g.enhanced_conversion_data,d=(a||{}).enhanced_conversions_mode;if(g.Promise)try{return c?kf(c,b).then(function(e){e.ce=d;return e}):Promise.resolve({mc:"",$b:[],ce:d})}catch(e){}};
var gi=function(a){if(K(H.D))return a;a=a.replace(/&url=([^&#]+)/,function(b,c){var d=xe(decodeURIComponent(c));return"&url="+encodeURIComponent(d)});a=a.replace(/&ref=([^&#]+)/,function(b,c){var d=xe(decodeURIComponent(c));return"&ref="+encodeURIComponent(d)});return a},hi=function(){var a;if(!(a=tf)){var b;if(!0===g._gtmdgs)b=!0;else{var c=vb&&vb.userAgent||"";b=0>c.indexOf("Safari")||/Chrome|Coast|Opera|Edg|Silk|Android/.test(c)||
11>((/Version\/([\d]+)/.exec(c)||[])[1]||"")?!1:!0}a=!b}if(a)return-1;var d=La("1");return Sf(1,100)<d?Sf(2,2):-1},ii=function(a){var b;if(!a||!a.length)return;for(var c=[],d=0;d<a.length;++d){var e=a[d];e&&e.estimated_delivery_date?c.push(""+e.estimated_delivery_date):c.push("")}b=c.join(",");return b};var ji=new RegExp(/^(.*\.)?(google|youtube|blogger|withgoogle)(\.com?)?(\.[a-z]{2})?\.?$/),ki={cl:["ecl"],customPixels:["nonGooglePixels"],ecl:["cl"],ehl:["hl"],hl:["ehl"],html:["customScripts","customPixels","nonGooglePixels","nonGoogleScripts","nonGoogleIframes"],customScripts:["html","customPixels","nonGooglePixels","nonGoogleScripts","nonGoogleIframes"],nonGooglePixels:[],nonGoogleScripts:["nonGooglePixels"],nonGoogleIframes:["nonGooglePixels"]},li={cl:["ecl"],customPixels:["customScripts","html"],
ecl:["cl"],ehl:["hl"],hl:["ehl"],html:["customScripts"],customScripts:["html"],nonGooglePixels:["customPixels","customScripts","html","nonGoogleScripts","nonGoogleIframes"],nonGoogleScripts:["customScripts","html"],nonGoogleIframes:["customScripts","html","nonGoogleScripts"]},mi="google customPixels customScripts html nonGooglePixels nonGoogleScripts nonGoogleIframes".split(" ");
var ni=function(){var a=!1;return a},pi=function(a){var b=Ff("gtm.allowlist")||Ff("gtm.whitelist");b&&td(9);ni()&&(b="google gtagfl lcl zone oid op".split(" "));var c=b&&Ya(Na(b),ki),d=Ff("gtm.blocklist")||
Ff("gtm.blacklist");d||(d=Ff("tagTypeBlacklist"))&&td(3);d?td(8):d=[];oi()&&(d=Na(d),d.push("nonGooglePixels","nonGoogleScripts","sandboxedScripts"));0<=ya(Na(d),"google")&&td(2);var e=d&&Ya(Na(d),li),f={};return function(h){var k=h&&h[Xb.kb];if(!k||"string"!=typeof k)return!0;k=k.replace(/^_*/,"");if(void 0!==f[k])return f[k];var l=yf[k]||[],n=a(k,l);if(b){var p;if(p=
n)a:{if(0>ya(c,k))if(l&&0<l.length)for(var r=0;r<l.length;r++){if(0>ya(c,l[r])){td(11);p=!1;break a}}else{p=!1;break a}p=!0}n=p}var t=!1;if(d){var q=0<=ya(e,k);if(q)t=q;else{var v=Ea(e,l||[]);v&&td(10);t=v}}var u=!n||t;u||!(0<=ya(l,"sandboxedScripts"))||c&&-1!==ya(c,"sandboxedScripts")||(u=Ea(e,mi));return f[k]=u}},oi=function(){return ji.test(g.location&&g.location.hostname)};var qi={active:!0,isAllowed:function(){return!0}},ri=function(a){var b=mf.zones;return b?b.checkState(lf.M,a):qi},si=function(a){var b=mf.zones;!b&&a&&(b=mf.zones=a());return b};var ti=function(){},ui=function(){};var vi=!1,wi=0,xi=[];function yi(a){if(!vi){var b=m.createEventObject,c="complete"==m.readyState,d="interactive"==m.readyState;if(!a||"readystatechange"!=a.type||c||!b&&d){vi=!0;for(var e=0;e<xi.length;e++)C(xi[e])}xi.push=function(){for(var f=0;f<arguments.length;f++)C(arguments[f]);return 0}}}function zi(){if(!vi&&140>wi){wi++;try{m.documentElement.doScroll("left"),yi()}catch(a){g.setTimeout(zi,50)}}}var Ai=function(a){vi?a():xi.push(a)};var Ci=function(a,b){this.o=!1;this.F=[];this.P={tags:[]};this.aa=!1;this.s=this.C=0;Bi(this,a,b)},Di=function(a,b,c,d){if(pf.hasOwnProperty(b)||"__zone"===b)return-1;var e={};Vb(d)&&(e=E(d,e));e.id=c;e.status="timeout";return a.P.tags.push(e)-1},Ei=function(a,b,c,d){var e=a.P.tags[b];e&&(e.status=c,e.executionTime=d)},Fi=function(a){if(!a.o){for(var b=a.F,c=0;c<b.length;c++)b[c]();a.o=!0;a.F.length=0}},Bi=function(a,b,c){ua(b)&&Gi(a,b);c&&g.setTimeout(function(){return Fi(a)},Number(c))},Gi=function(a,
b){var c=Va(function(){return C(function(){b(lf.M,a.P)})});a.o?c():a.F.push(c)},Hi=function(a){a.C++;return Va(function(){a.s++;a.aa&&a.s>=a.C&&Fi(a)})};var Ii=function(){function a(d){return!wa(d)||0>d?0:d}if(!mf._li&&g.performance&&g.performance.timing){var b=g.performance.timing.navigationStart,c=wa(Gf.get("gtm.start"))?Gf.get("gtm.start"):0;mf._li={cst:a(c-b),cbt:a(vf-b)}}},Ji=function(a){g.performance&&g.performance.mark(lf.M+"_"+a+"_start")},Ki=function(a){if(g.performance){var b=lf.M+"_"+a+"_start",c=lf.M+"_"+a+"_duration";g.performance.measure(c,b);var d=g.performance.getEntriesByName(c)[0];g.performance.clearMarks(b);g.performance.clearMeasures(c);
var e=mf._p||{};void 0===e[a]&&(e[a]=d.duration,mf._p=e);return d.duration}},Li=function(){if(g.performance&&g.performance.now){var a=mf._p||{};a.PAGEVIEW=g.performance.now();mf._p=a}};var Mi={},Ni=function(){return g.GoogleAnalyticsObject&&g[g.GoogleAnalyticsObject]},Oi=!1;
var Pi=function(a){g.GoogleAnalyticsObject||(g.GoogleAnalyticsObject=a||"ga");var b=g.GoogleAnalyticsObject;if(g[b])g.hasOwnProperty(b)||td(12);else{var c=function(){c.q=c.q||[];c.q.push(arguments)};c.l=Number(Pa());g[b]=c}Ii();return g[b]},Qi=function(a,b,c,d){b=String(b).replace(/\s+/g,"").split(",");var e=Ni();e(a+"require","linker");e(a+"linker:autoLink",b,c,d)},Ri=function(a){if(!Od())return;var b=Ni();b(a+"require","linker");b(a+"linker:passthrough",
!0);};
var Ti=function(a){},Si=function(){return g.GoogleAnalyticsObject||"ga"},Ui=function(a,b){return function(){var c=Ni(),d=c&&c.getByName&&c.getByName(a);if(d){var e=d.get("sendHitTask");d.set("sendHitTask",function(f){var h=f.get("hitPayload"),k=f.get("hitCallback"),l=0>h.indexOf("&tid="+b);l&&(f.set("hitPayload",h.replace(/&tid=UA-[0-9]+-[0-9]+/,"&tid="+
b),!0),f.set("hitCallback",void 0,!0));e(f);l&&(f.set("hitPayload",h,!0),f.set("hitCallback",k,!0),f.set("_x_19",void 0,!0),e(f))})}}};
var ej=function(a){},ij=function(a){},jj=
function(){return"&tc="+Dc.filter(function(a){return a}).length},mj=function(){2022<=kj().length&&lj()},nj=function(a){return 0===a.indexOf("gtm.")?encodeURIComponent(a):"*"},pj=function(){oj||(oj=g.setTimeout(lj,500))},lj=function(){oj&&(g.clearTimeout(oj),oj=void 0);void 0===qj||rj[qj]&&!sj&&!tj||(uj[qj]||vj.bi()||0>=wj--?(td(1),uj[qj]=!0):(vj.wi(),Eb(kj(!0)),rj[qj]=!0,xj=yj=zj=tj=sj=""))},kj=function(a){var b=qj;if(void 0===b)return"";var c=sa("GTM"),d=sa("TAGGING");return[Aj,rj[b]?"":"&es=1",
Bj[b],ej(b),c?"&u="+c:"",d?"&ut="+d:"",jj(),sj,tj,zj,yj,ij(a),xj,"&z=0"].join("")},Dj=function(){Aj=Cj()},Cj=function(){return[wf,"&v=3&t=t","&pid="+Aa(),"&rv="+lf.Vc].join("")},hj=["L","S","Y"],dj=["S","E"],Ej={sampleRate:"0.005000",rg:"",qg:Number("5")},Fj=0<=m.location.search.indexOf("?gtm_latency=")||0<=m.location.search.indexOf("&gtm_latency="),Gj;if(!(Gj=Fj)){var Hj=Math.random(),Ij=Ej.sampleRate;Gj=Hj<Ij}var Jj=Gj,Kj={label:lf.M+" Container",children:[{label:"Initialization",children:[]}]},Aj=Cj(),rj={},sj="",tj="",xj="",yj="",gj={},fj=!1,cj={},Lj={},zj="",qj=void 0,Bj={},uj={},oj=void 0,Mj=2;0<Ej.qg&&(Mj=Ej.qg);var vj=function(a,b){for(var c=0,d=[],e=0;e<a;++e)d.push(0);
return{bi:function(){return c<a?!1:Ra()-d[c%a]<b},wi:function(){var f=c++%a;d[f]=Ra()}}}(Mj,1E3),wj=1E3,Oj=function(a,b){if(Jj&&!uj[a]&&qj!==a){lj();qj=a;xj=sj="";Bj[a]="&e="+nj(b)+"&eid="+a;pj();}},Pj=function(a,b,c,d){if(Jj&&b){var e,f=String(b[Xb.kb]||
"").replace(/_/g,"");0===f.indexOf("cvt")&&(f="cvt");e=f;var h=c+e;if(!uj[a]){a!==qj&&(lj(),qj=a);sj=sj?sj+"."+h:"&tr="+h;var k=b["function"];if(!k)throw Error("Error: No function name given for function call.");
var l=(Fc[k]?"1":"2")+e;xj=xj?xj+"."+l:"&ti="+l;pj();mj()}}};var Wj=function(a,b,c){if(Jj&&!uj[a]){a!==qj&&(lj(),
qj=a);var d=c+b;tj=tj?tj+"."+d:"&epr="+d;pj();mj()}},Xj=function(a,b,c){};function Yj(a,b,c,d){var e=Dc[a],f=Zj(a,b,c,d);if(!f)return null;var h=Kc(e[Xb.yf],c,[]);if(h&&h.length){var k=h[0];f=Yj(k.index,{onSuccess:f,onFailure:1===k.Rf?b.terminate:f,terminate:b.terminate},c,d)}return f}
function Zj(a,b,c,d){function e(){if(f[Xb.mh])k();else{var w=Lc(f,c,[]);var y=w[Xb.xg];if(null!=y)for(var x=0;x<y.length;x++)if(!K(y[x])){k();return}var z=Di(c.lb,String(f[Xb.kb]),Number(f[Xb.zf]),w[Xb.nh]),A=!1;w.vtp_gtmOnSuccess=function(){if(!A){A=!0;var F=Ra()-D;Pj(c.id,Dc[a],"5",F);Ei(c.lb,z,"success",
F);h()}};w.vtp_gtmOnFailure=function(){if(!A){A=!0;var F=Ra()-D;Pj(c.id,Dc[a],"6",F);Ei(c.lb,z,"failure",F);k()}};w.vtp_gtmTagId=f.tag_id;w.vtp_gtmEventId=c.id;Pj(c.id,f,"1");var B=function(){var F=Ra()-D;Pj(c.id,f,"7",F);Ei(c.lb,z,"exception",F);A||(A=!0,k())};var D=Ra();try{Jc(w,c)}catch(F){B(F)}}}var f=Dc[a],h=b.onSuccess,k=b.onFailure,l=b.terminate;if(c.se(f))return null;var n=Kc(f[Xb.Af],c,[]);if(n&&n.length){var p=n[0],r=Yj(p.index,{onSuccess:h,onFailure:k,terminate:l},c,d);if(!r)return null;h=r;k=2===p.Rf?l:r}if(f[Xb.uf]||f[Xb.ph]){var t=f[Xb.uf]?Ec:
c.Di,q=h,v=k;if(!t[a]){e=Va(e);var u=ak(a,t,e);h=u.onSuccess;k=u.onFailure}return function(){t[a](q,v)}}return e}function ak(a,b,c){var d=[],e=[];b[a]=bk(d,e,c);return{onSuccess:function(){b[a]=ck;for(var f=0;f<d.length;f++)d[f]()},onFailure:function(){b[a]=dk;for(var f=0;f<e.length;f++)e[f]()}}}function bk(a,b,c){return function(d,e){a.push(d);b.push(e);c()}}function ck(a){a()}function dk(a,b){b()};var gk=function(a,b){for(var c=[],d=0;d<Dc.length;d++)if(a[d]){var e=Dc[d];var f=Hi(b.lb);try{var h=Yj(d,{onSuccess:f,onFailure:f,terminate:f},b,d);if(h){var k=c,l=k.push,n=d,p=e["function"];if(!p)throw"Error: No function name given for function call.";var r=Fc[p];l.call(k,{mg:n,bg:r?r.priorityOverride||0:0,Oh:h})}else ek(d,b),f()}catch(v){f()}}var t=b.lb;t.aa=!0;t.s>=t.C&&Fi(t);c.sort(fk);for(var q=0;q<c.length;q++)c[q].Oh();
return 0<c.length};function fk(a,b){var c,d=b.bg,e=a.bg;c=d>e?1:d<e?-1:0;var f;if(0!==c)f=c;else{var h=a.mg,k=b.mg;f=h>k?1:h<k?-1:0}return f}function ek(a,b){if(!Jj)return;var c=function(d){var e=b.se(Dc[d])?"3":"4",f=Kc(Dc[d][Xb.yf],b,[]);f&&f.length&&c(f[0].index);Pj(b.id,Dc[d],e);var h=Kc(Dc[d][Xb.Af],b,[]);h&&h.length&&c(h[0].index)};c(a);}
var hk=!1,nk=function(a){var b=Ra(),c=a["gtm.uniqueEventId"],d=a.event;if("gtm.js"===d){if(hk)return!1;hk=!0;}var h=ri(c),k=!1;if(!h.active){if("gtm.js"!==d)return!1;k=!0;h=ri(Number.MAX_SAFE_INTEGER)}
Oj(c,d);var l=a.eventCallback,n=a.eventTimeout,p=l;var r={id:c,name:d,se:pi(h.isAllowed),Di:[],Yf:function(){td(6)},Kf:ik(c),lb:new Ci(p,n)};r.Jf=jk();
kk(c,r.lb);var t=Pc(r);k&&(t=lk(t));var q=gk(t,r);"gtm.js"!==d&&"gtm.sync"!==d||Ti(lf.M);switch(d){case "gtm.init":q&&td(20)}return mk(t,q)};function ik(a){return function(b){Jj&&(Wb(b)||Xj(a,"input",b))}}
function kk(a,b){Kf(a,"event",1);Kf(a,"ecommerce",1);Kf(a,"gtm");Kf(a,"eventModel");}function jk(){var a={};a.event=Jf("event",1);a.ecommerce=Jf("ecommerce",1);a.gtm=Jf("gtm");a.eventModel=Jf("eventModel");return a}function lk(a){for(var b=[],c=0;c<a.length;c++)a[c]&&of[String(Dc[c][Xb.kb])]&&(b[c]=!0);return b}
function mk(a,b){if(!b)return b;for(var c=0;c<a.length;c++)if(a[c]&&Dc[c]&&!pf[String(Dc[c][Xb.kb])])return!0;return!1}function ok(a,b){if(a){var c=""+a;0!==c.indexOf("http://")&&0!==c.indexOf("https://")&&(c="https://"+c);"/"===c[c.length-1]&&(c=c.substring(0,c.length-1));return we(""+c+b).href}}function pk(a,b){return qk()?ok(a,b):void 0}function qk(){var a=!1;return a};var rk=function(){this.eventModel={};this.targetConfig={};this.containerConfig={};this.remoteConfig={};this.globalConfig={};this.onSuccess=function(){};this.onFailure=function(){};this.setContainerTypeLoaded=function(){};this.getContainerTypeLoaded=function(){};this.eventId=void 0;this.isGtmEvent=!1},sk=function(a){var b=new rk;b.eventModel=a;return b},tk=function(a,b){a.targetConfig=b;return a},uk=function(a,b){a.containerConfig=b;return a},vk=function(a,b){a.remoteConfig=b;return a},wk=function(a,
b){a.globalConfig=b;return a},xk=function(a,b){a.onSuccess=b;return a},yk=function(a,b){a.setContainerTypeLoaded=b;return a},zk=function(a,b){a.getContainerTypeLoaded=b;return a},Ak=function(a,b){a.onFailure=b;return a};
rk.prototype.getWithConfig=function(a){if(void 0!==this.eventModel[a])return this.eventModel[a];if(void 0!==this.targetConfig[a])return this.targetConfig[a];if(void 0!==this.containerConfig[a])return this.containerConfig[a];if(void 0!==this.remoteConfig[a])return this.remoteConfig[a];if(void 0!==this.globalConfig[a])return this.globalConfig[a]};
var Bk=function(a){function b(e){Ha(e,function(f){c[f]=null})}var c={};b(a.eventModel);b(a.targetConfig);b(a.containerConfig);b(a.globalConfig);var d=[];Ha(c,function(e){d.push(e)});return d},Ck=function(a,b){function c(f){Vb(f)&&Ha(f,function(h,k){e=!0;d[h]=k})}var d={},e=!1;c(a.globalConfig[b]);c(a.remoteConfig[b]);c(a.containerConfig[b]);c(a.targetConfig[b]);c(a.eventModel[b]);return e?d:void 0};var Dk;if(3===lf.Vc.length)Dk="g";else{var Ek="G";Dk=Ek}
var Fk={"":"n",UA:"u",AW:"a",DC:"d",G:"e",GF:"f",HA:"h",GTM:Dk,OPT:"o"},Gk=function(a){var b=lf.M.split("-"),c=b[0].toUpperCase(),d=Fk[c]||"i",e=a&&"GTM"===c?b[1]:"OPT"===c?b[1]:"",f;if(3===lf.Vc.length){var h="w";f="2"+h}else f="";return f+d+lf.Vc+e};function Hk(a,b){if(""===a)return b;var c=Number(a);return isNaN(c)?b:c};var Ik=function(a,b){a.addEventListener&&a.addEventListener.call(a,"message",b,!1)};var Jk=function(){return lb("iPhone")&&!lb("iPod")&&!lb("iPad")};lb("Opera");lb("Trident")||lb("MSIE");lb("Edge");!lb("Gecko")||-1!=hb.toLowerCase().indexOf("webkit")&&!lb("Edge")||lb("Trident")||lb("MSIE")||lb("Edge");-1!=hb.toLowerCase().indexOf("webkit")&&!lb("Edge")&&lb("Mobile");lb("Macintosh");lb("Windows");lb("Linux")||lb("CrOS");var Kk=na.navigator||null;Kk&&(Kk.appVersion||"").indexOf("X11");lb("Android");Jk();lb("iPad");lb("iPod");Jk()||lb("iPad")||lb("iPod");hb.toLowerCase().indexOf("kaios");var Lk=function(a,b){for(var c=a,d=0;50>d;++d){var e;try{e=!(!c.frames||!c.frames[b])}catch(k){e=!1}if(e)return c;var f;a:{try{var h=c.parent;if(h&&h!=c){f=h;break a}}catch(k){}f=null}if(!(c=f))break}return null},Mk=function(a){var b=m;b=void 0===b?window.document:b;if(!a||!b.head)return null;var c=document.createElement("meta");b.head.appendChild(c);c.httpEquiv="origin-trial";c.content=a;return c};var Nk=function(){};var Ok=function(a){void 0!==a.addtlConsent&&"string"!==typeof a.addtlConsent&&(a.addtlConsent=void 0);void 0!==a.gdprApplies&&"boolean"!==typeof a.gdprApplies&&(a.gdprApplies=void 0);return void 0!==a.tcString&&"string"!==typeof a.tcString||void 0!==a.listenerId&&"number"!==typeof a.listenerId?2:a.cmpStatus&&"error"!==a.cmpStatus?0:3},Pk=function(a,b){this.s=a;this.o=null;this.F={};this.aa=0;this.P=void 0===b?500:b;this.C=null};la(Pk,Nk);
var Rk=function(a){return"function"===typeof a.s.__tcfapi||null!=Qk(a)};
Pk.prototype.addEventListener=function(a){var b={},c=sb(function(){return a(b)}),d=0;-1!==this.P&&(d=setTimeout(function(){b.tcString="tcunavailable";b.internalErrorState=1;c()},this.P));var e=function(f,h){clearTimeout(d);f?(b=f,b.internalErrorState=Ok(b),h&&0===b.internalErrorState||(b.tcString="tcunavailable",h||(b.internalErrorState=3))):(b.tcString="tcunavailable",b.internalErrorState=3);a(b)};try{Sk(this,"addEventListener",e)}catch(f){b.tcString="tcunavailable",b.internalErrorState=3,d&&(clearTimeout(d),
d=0),c()}};Pk.prototype.removeEventListener=function(a){a&&a.listenerId&&Sk(this,"removeEventListener",null,a.listenerId)};
var Uk=function(a,b,c){var d;d=void 0===d?"755":d;var e;a:{if(a.publisher&&a.publisher.restrictions){var f=a.publisher.restrictions[b];if(void 0!==f){e=f[void 0===d?"755":d];break a}}e=void 0}var h=e;if(0===h)return!1;var k=c;2===c?(k=0,2===h&&(k=1)):3===c&&(k=1,1===h&&(k=0));var l;if(0===k)if(a.purpose&&a.vendor){var n=Tk(a.vendor.consents,void 0===d?"755":d);l=n&&"1"===b&&a.purposeOneTreatment&&("DE"===a.publisherCC||Dd(vd)&&"CH"===a.publisherCC)?!0:n&&Tk(a.purpose.consents,b)}else l=!0;else l=
1===k?a.purpose&&a.vendor?Tk(a.purpose.legitimateInterests,b)&&Tk(a.vendor.legitimateInterests,void 0===d?"755":d):!0:!0;return l},Tk=function(a,b){return!(!a||!a[b])},Sk=function(a,b,c,d){c||(c=function(){});if("function"===typeof a.s.__tcfapi){var e=a.s.__tcfapi;e(b,2,c,d)}else if(Qk(a)){Vk(a);var f=++a.aa;a.F[f]=c;if(a.o){var h={};a.o.postMessage((h.__tcfapiCall={command:b,version:2,callId:f,parameter:d},h),"*")}}else c({},!1)},Qk=function(a){if(a.o)return a.o;a.o=Lk(a.s,"__tcfapiLocator");return a.o},
Vk=function(a){a.C||(a.C=function(b){try{var c;c=("string"===typeof b.data?JSON.parse(b.data):b.data).__tcfapiReturn;a.F[c.callId](c.returnValue,c.success)}catch(d){}},Ik(a.s,a.C))};var Wk=!0;Wk=!1;var Xk={1:0,3:0,4:0,7:3,9:3,10:3},Yk=Hk("",550),Zk=Hk("",500);function $k(){var a=mf.tcf||{};return mf.tcf=a}
var al=function(a,b){this.C=a;this.o=b;this.s=Ra();},bl=function(a){},cl=function(a){},il=function(){var a=$k(),b=new Pk(g,Wk?3E3:-1),c=new al(b,a);if((dl()?!0===g.gtag_enable_tcf_support:!1!==g.gtag_enable_tcf_support)&&!a.active&&("function"===typeof g.__tcfapi||Rk(b))){a.active=!0;a.oc={};el();var d=null;Wk?d=g.setTimeout(function(){fl(a);gl(a);d=null},Zk):a.tcString="tcunavailable";try{b.addEventListener(function(e){d&&(clearTimeout(d),d=null);if(0!==e.internalErrorState)fl(a),gl(a),bl(c);
else{var f;a.gdprApplies=e.gdprApplies;if(!1===e.gdprApplies)f=hl(),b.removeEventListener(e);else if("tcloaded"===e.eventStatus||"useractioncomplete"===e.eventStatus||"cmpuishown"===e.eventStatus){var h={},k;for(k in Xk)if(Xk.hasOwnProperty(k))if("1"===k){var l,n=e,p=!0;p=void 0===p?!1:p;var r;var t=n;!1===t.gdprApplies?r=!0:(void 0===t.internalErrorState&&(t.internalErrorState=Ok(t)),r="error"===t.cmpStatus||0!==t.internalErrorState||"loaded"===t.cmpStatus&&("tcloaded"===t.eventStatus||"useractioncomplete"===
t.eventStatus)?!0:!1);l=r?!1===n.gdprApplies||"tcunavailable"===n.tcString||void 0===n.gdprApplies&&!p||"string"!==typeof n.tcString||!n.tcString.length?!0:Uk(n,"1",0):!1;h["1"]=l}else h[k]=Uk(e,k,Xk[k]);f=h}f&&(a.tcString=e.tcString||"tcempty",a.oc=f,gl(a),bl(c))}}),cl(c)}catch(e){d&&(clearTimeout(d),d=null),fl(a),gl(a)}}};function fl(a){a.type="e";a.tcString="tcunavailable";Wk&&(a.oc=hl())}function el(){var a={},b=(a.ad_storage="denied",a.wait_for_update=Yk,a);Wd(b)}
var dl=function(){var a=!1;a=!0;return a};function hl(){var a={},b;for(b in Xk)Xk.hasOwnProperty(b)&&(a[b]=!0);return a}function gl(a){var b={},c=(b.ad_storage=a.oc["1"]?"granted":"denied",b);jl();Xd(c,0)}
var kl=function(){var a=$k();if(a.active&&void 0!==a.loadTime)return Number(a.loadTime)},jl=function(){var a=$k();return a.active?a.tcString||"":""},ll=function(){var a=$k();return a.active&&void 0!==a.gdprApplies?a.gdprApplies?"1":"0":""},ml=function(a){if(!Xk.hasOwnProperty(String(a)))return!0;var b=$k();return b.active&&b.oc?!!b.oc[String(a)]:!0};var nl=!1;nl=!0;function ol(a){var b=String(g.location).split(/[?#]/)[0],c=lf.Ag||g._CONSENT_MODE_SALT,d;if(a){var e;if(c){var f=b+a+c,h=1,k,l,n;if(f)for(h=0,l=f.length-1;0<=l;l--)n=f.charCodeAt(l),h=(h<<6&268435455)+n+(n<<14),k=h&266338304,h=0!=k?h^k>>21:h;e=String(h)}else e="0";d=e}else d="";return d}
function pl(a){function b(v){var u;mf.reported_gclid||(mf.reported_gclid={});u=mf.reported_gclid;var w;w=nl&&h&&(!Od()||K(H.D))?l+"."+(f.prefix||"_gcl")+(v?"gcu":"gcs"):l+(v?"gcu":"gcs");if(!u[w]){u[w]=!0;var y=[],x={},z=function(N,S){S&&(y.push(N+"="+encodeURIComponent(S)),x[N]=!0)},A="https://www.google.com";if(Od()){var B=K(H.D);z("gcs",Yd());v&&z("gcu","1");Pd()&&z("gcd","G1"+Ud(Md));mf.dedupe_gclid||
(mf.dedupe_gclid=""+ig());z("rnd",mf.dedupe_gclid);if((!l||n&&"aw.ds"!==n)&&K(H.D)){var D=kh("_gcl_aw");z("gclaw",D.join("."))}z("url",String(g.location).split(/[?#]/)[0]);z("dclid",ql(d,p));var F=!1;F=!0;B||!d&&!F||(A="https://pagead2.googlesyndication.com")}
z("gdpr_consent",jl()),z("gdpr",ll());"1"===Vg(!1)._up&&z("gtm_up","1");z("gclid",ql(d,l));z("gclsrc",n);if(!(x.gclid||x.dclid||x.gclaw)&&(z("gbraid",ql(d,r)),!x.gbraid&&Od()&&K(H.D))){var G=kh("_gcl_gb");z("gclgb",G.join("."))}z("gtm",Gk(!e));nl&&h&&K(H.D)&&(xg(f||{}),z("auid",tg[ug(f.prefix)]||""));
a.Nf&&z("did",a.Nf);var J=A+"/pagead/landing?"+y.join("&");Qb(J)}}var c=!!a.de,d=!!a.ra,e=a.T,f=void 0===a.$c?{}:a.$c,h=void 0===a.gd?!0:a.gd,k=qh(),l=k.gclid||"",n=k.gclsrc,p=k.dclid||"",r=k.gbraid||"",t=!c&&((!l||n&&"aw.ds"!==n?!1:!0)||r),q=Od();if(t||q)q?$d(function(){b();K(H.D)||Zd(function(v){return b(!0,v.Dh)},H.D)},[H.D]):b()}function ql(a,b){var c=a&&!K(H.D);return b&&c?"0":b}var rl=function(){this.o={}},sl=function(a,b,c){null!=c&&(a.o[b]=c)},tl=function(a){return Object.keys(a.o).map(function(b){return encodeURIComponent(b)+"="+encodeURIComponent(a.o[b])}).join("&")},vl=function(a,b,c,d){};var xl=!1,yl=Number("200");function zl(){if(!g.Promise)return!1;ua(m.interestCohort)||xl||(xl=!0,Mk("A489+ZNTpP/HCOD+k3I13nobRVH7eyh5fz5LGhYvQlNf9WauHk/0awCtXOEoWTIK9JN8bgzgn2SfPdaFXe5O9QkAAACKeyJvcmlnaW4iOiJodHRwczovL3d3dy5nb29nbGV0YWdtYW5hZ2VyLmNvbTo0NDMiLCJmZWF0dXJlIjoiSW50ZXJlc3RDb2hvcnRBUEkiLCJleHBpcnkiOjE2MjYyMjA3OTksImlzU3ViZG9tYWluIjp0cnVlLCJpc1RoaXJkUGFydHkiOnRydWV9"));return ua(m.interestCohort)}
function Al(){var a=mf.floc;if(a){var b=a.ts,c=a.floc;if(b&&c&&1E3>Ra()-b)return Promise.resolve(c)}var d=void 0;try{d=Promise.race([m.interestCohort().then(function(e){mf.floc={ts:Ra(),floc:e};return e}),new Promise(function(e){g.setTimeout(function(){return e()},yl)})]).catch(function(){})}catch(e){return}return d}var ym=function(){var a=!0;ml(7)&&ml(9)&&ml(10)||(a=!1);var b=!0;b=!1;b&&!xm()&&(a=!1);return a},xm=function(){var a=!0;ml(3)&&ml(4)||(a=!1);return a};var $m=!1;var an=!1;function bn(){var a=mf;return a.gcq=a.gcq||new cn}
var dn=function(a,b,c){bn().register(a,b,c)},en=function(a,b,c,d){bn().push("event",[b,a],c,d)},fn=function(a,b){bn().push("config",[a],b)},gn=function(a,b,c,d){bn().push("get",[a,b],c,d)},hn={},jn=function(){this.status=1;this.containerConfig={};this.targetConfig={};this.remoteConfig={};this.s={};this.C=null;this.o=!1},kn=function(a,b,c,d,e){this.type=a;this.C=b;this.T=c||"";this.o=d;this.s=e},cn=function(){this.s={};this.C={};this.o=[];this.F={AW:!1,UA:!1};this.enableDeferrableCommandAfterConfig=
$m},ln=function(a,b){var c=Ph(b);return a.s[c.containerId]=a.s[c.containerId]||new jn},mn=function(a,b,c){if(b){var d=Ph(b);if(d&&1===ln(a,b).status){ln(a,b).status=2;var e={};Jj&&(e.timeoutId=g.setTimeout(function(){td(38);pj()},3E3));a.push("require",[e],d.containerId);hn[d.containerId]=Ra();if(Sh()){}else{var h="/gtag/js?id="+encodeURIComponent(d.containerId)+"&l=dataLayer&cx=c",k=("http:"!=g.location.protocol?"https:":"http:")+("//www.googletagmanager.com"+h),l=pk(c,h)||k;Bb(l)}}}},nn=function(a,b,c,d){if(d.T){var e=ln(a,d.T),f=e.C;if(f){var h=E(c),k=E(e.targetConfig[d.T]),l=E(e.containerConfig),n=E(e.remoteConfig),p=E(a.C),r=Ff("gtm.uniqueEventId"),t=Ph(d.T).prefix,q=Va(function(){var u=h[H.xb];u&&C(u)}),v=zk(yk(Ak(xk(wk(vk(uk(tk(sk(h),k),l),n),p),function(){
Wj(r,t,"2");an&&q()}),function(){Wj(r,t,"3");an&&q()}),function(u,w){a.F[u]=w}),function(u){return a.F[u]});try{Wj(r,t,"1");f(d.T,b,d.C,v)}catch(u){Wj(r,t,"4");}}}};
cn.prototype.register=function(a,b,c){var d=ln(this,a);if(3!==d.status){d.C=b;d.status=3;if(c){E(d.remoteConfig,c);d.remoteConfig=c}var e=Ph(a),f=hn[e.containerId];if(void 0!==f){var h=mf[e.containerId].bootstrap,k=e.prefix.toUpperCase();mf[e.containerId]._spx&&(k=k.toLowerCase());var l=Ff("gtm.uniqueEventId"),n=k,p=Ra()-h;if(Jj&&!uj[l]){l!==qj&&(lj(),qj=l);var r=n+"."+Math.floor(h-
f)+"."+Math.floor(p);yj=yj?yj+","+r:"&cl="+r}delete hn[e.containerId]}this.flush()}};cn.prototype.push=function(a,b,c,d){var e=Math.floor(Ra()/1E3);mn(this,c,b[0][H.na]||this.C[H.na]);$m&&c&&ln(this,c).o&&(d=!1);this.o.push(new kn(a,e,c,b,d));d||this.flush()};cn.prototype.insert=function(a,b,c){var d=Math.floor(Ra()/1E3);0<this.o.length?this.o.splice(1,0,new kn(a,d,c,b,!1)):this.o.push(new kn(a,d,c,b,!1))};
cn.prototype.flush=function(a){for(var b=this,c=[],d=!1,e={};this.o.length;){var f=this.o[0];if(f.s)$m?!f.T||ln(this,f.T).o?(f.s=!1,this.o.push(f)):c.push(f):(f.s=!1,this.o.push(f)),this.o.shift();else{switch(f.type){case "require":if(3!==ln(this,f.T).status&&!a){$m&&this.o.push.apply(this.o,c);return}Jj&&g.clearTimeout(f.o[0].timeoutId);break;case "set":Ha(f.o[0],function(t,q){E(Za(t,q),b.C)});break;case "config":e.Ia={};Ha(f.o[0],function(t){return function(q,v){E(Za(q,v),t.Ia)}}(e));var h=!!e.Ia[H.Nc];
delete e.Ia[H.Nc];var k=ln(this,f.T),l=Ph(f.T),n=l.containerId===l.id;h||(n?k.containerConfig={}:k.targetConfig[f.T]={});k.o&&h||nn(this,H.Ca,e.Ia,f);k.o=!0;delete e.Ia[H.Ub];n?E(e.Ia,k.containerConfig):E(e.Ia,k.targetConfig[f.T]);$m&&(d=!0);break;case "event":e.vc={};Ha(f.o[0],function(t){return function(q,v){E(Za(q,v),t.vc)}}(e));nn(this,f.o[1],e.vc,f);break;case "get":var p={},r=(p[H.Ua]=f.o[0],p[H.Ta]=f.o[1],p);nn(this,H.Ka,r,f)}this.o.shift();on(this,f)}e={Ia:e.Ia,vc:e.vc}}$m&&(this.o.push.apply(this.o,
c),d&&this.flush())};var on=function(a,b){if("require"!==b.type)if(b.T)for(var c=a.getCommandListeners(b.T)[b.type]||[],d=0;d<c.length;d++)c[d]();else for(var e in a.s)if(a.s.hasOwnProperty(e)){var f=a.s[e];if(f&&f.s)for(var h=f.s[b.type]||[],k=0;k<h.length;k++)h[k]()}};cn.prototype.getRemoteConfig=function(a){return ln(this,a).remoteConfig};cn.prototype.getCommandListeners=function(a){return ln(this,a).s};var pn=function(a,b,c){var d={event:b,"gtm.element":a,"gtm.elementClasses":Rb(a,"className"),"gtm.elementId":a["for"]||Hb(a,"id")||"","gtm.elementTarget":a.formTarget||Rb(a,"target")||""};c&&(d["gtm.triggers"]=c.join(","));d["gtm.elementUrl"]=(a.attributes&&a.attributes.formaction?a.formAction:"")||a.action||Rb(a,"href")||a.src||a.code||a.codebase||"";return d},qn=function(a){mf.hasOwnProperty("autoEventsSettings")||(mf.autoEventsSettings={});var b=mf.autoEventsSettings;b.hasOwnProperty(a)||(b[a]=
{});return b[a]},rn=function(a,b,c){qn(a)[b]=c},sn=function(a,b,c,d){var e=qn(a),f=Sa(e,b,d);e[b]=c(f)},tn=function(a,b,c){var d=qn(a);return Sa(d,b,c)};var un=["input","select","textarea"],vn=["button","hidden","image","reset","submit"],wn=function(a){var b=a.tagName.toLowerCase();return!za(un,function(c){return c===b})||"input"===b&&za(vn,function(c){return c===a.type.toLowerCase()})?!1:!0},xn=function(a){return a.form?a.form.tagName?a.form:m.getElementById(a.form):Kb(a,["form"],100)},yn=function(a,b,c){if(!a.elements)return 0;for(var d=b.dataset[c],e=0,f=1;e<a.elements.length;e++){var h=a.elements[e];if(wn(h)){if(h.dataset[c]===d)return f;f++}}return 0};var zn=!!g.MutationObserver,An=void 0,Bn=function(a){if(!An){var b=function(){var c=m.body;if(c)if(zn)(new MutationObserver(function(){for(var e=0;e<An.length;e++)C(An[e])})).observe(c,{childList:!0,subtree:!0});else{var d=!1;Fb(c,"DOMNodeInserted",function(){d||(d=!0,C(function(){d=!1;for(var e=0;e<An.length;e++)C(An[e])}))})}};An=[];m.body?b():C(b)}An.push(a)};var Dn=!1,En=[];function Fn(){if(!Dn){Dn=!0;for(var a=0;a<En.length;a++)C(En[a])}}var Gn=function(a){Dn?C(a):En.push(a)};function Hn(a,b){a=String(a);b=String(b);var c=a.length-b.length;return 0<=c&&a.indexOf(b,c)==c}var In=new Ca;function Jn(a,b,c){var d=c?"i":void 0;try{var e=String(b)+d,f=In.get(e);f||(f=new RegExp(b,d),In.set(e,f));return f.test(a)}catch(h){return!1}}
function Kn(a,b){function c(h){var k=we(h),l=ue(k,"protocol"),n=ue(k,"host",!0),p=ue(k,"port"),r=ue(k,"path").toLowerCase().replace(/\/$/,"");if(void 0===l||"http"==l&&"80"==p||"https"==l&&"443"==p)l="web",p="default";return[l,n,p,r]}for(var d=c(String(a)),e=c(String(b)),f=0;f<d.length;f++)if(d[f]!==e[f])return!1;return!0}
function Nn(a){return On(a)?1:0}
function On(a){var b=a.arg0,c=a.arg1;if(a.any_of&&xa(c)){for(var d=0;d<c.length;d++){var e=E(a,{});E({arg1:c[d],any_of:void 0},e);if(Nn(e))return!0}return!1}switch(a["function"]){case "_cn":return 0<=String(b).indexOf(String(c));case "_css":var f;a:{if(b){var h=["matches","webkitMatchesSelector","mozMatchesSelector","msMatchesSelector","oMatchesSelector"];try{for(var k=0;k<h.length;k++)if(b[h[k]]){f=b[h[k]](c);break a}}catch(n){}}f=!1}return f;case "_ew":return Hn(b,c);case "_eq":return String(b)==
String(c);case "_ge":return Number(b)>=Number(c);case "_gt":return Number(b)>Number(c);case "_lc":var l;l=String(b).split(",");return 0<=ya(l,String(c));case "_le":return Number(b)<=Number(c);case "_lt":return Number(b)<Number(c);case "_re":return Jn(b,c,a.ignore_case);case "_sw":return 0==String(b).indexOf(String(c));case "_um":return Kn(b,c)}return!1};Object.freeze({dl:1,id:1});var Pn="HA GF G UA AW DC".split(" "),Qn=!1;var Rn=!1,Sn={},Tn=!1;function Un(a,b){var c={event:a};b&&(c.eventModel=E(b),b[H.xb]&&(c.eventCallback=b[H.xb]),b[H.Fc]&&(c.eventTimeout=b[H.Fc]));return c}function Vn(a){a.hasOwnProperty("gtm.uniqueEventId")||Object.defineProperty(a,"gtm.uniqueEventId",{value:zf()});return a["gtm.uniqueEventId"]}
function Wn(){return Rn}
var Zn={config:function(a){var b,c;c=Vn(a);void 0===c&&(c=zf());return b},consent:function(a){function b(){Wn()&&E(a[2],{subcommand:a[1]})}if(3===a.length){td(39);var c=zf(),d=a[1];"default"===d?(b(),Wd(a[2])):"update"===d&&(b(),Xd(a[2],c))}},event:function(a){var b=a[1];if(!(2>
a.length)&&va(b)){var c;if(2<a.length){if(!Vb(a[2])&&void 0!=a[2]||3<a.length)return;c=a[2]}var d=Un(b,c),e=void 0;e=Vn(a),d["gtm.uniqueEventId"]=e;void 0===e&&zf();return d}},get:function(a){},js:function(a){if(2==a.length&&a[1].getTime){Tn=!0;Wn();var b={event:"gtm.js","gtm.start":a[1].getTime()};b["gtm.uniqueEventId"]=Vn(a);return b}},policy:function(){},
set:function(a){var b;2==a.length&&Vb(a[1])?b=E(a[1]):3==a.length&&va(a[1])&&(b={},Vb(a[2])||xa(a[2])?b[a[1]]=E(a[2]):b[a[1]]=a[2]);if(b){b._clear=!0;return b}}},$n={policy:!0};var ao=function(a,b){var c=a.hide;if(c&&void 0!==c[b]&&c.end){c[b]=!1;var d=!0,e;for(e in c)if(c.hasOwnProperty(e)&&!0===c[e]){d=!1;break}d&&(c.end(),c.end=null)}},co=function(a){var b=bo(),c=b&&b.hide;c&&c.end&&(c[a]=!0)};var uo=function(a){if(to(a))return a;this.o=a};uo.prototype.Uh=function(){return this.o};var to=function(a){return!a||"object"!==Tb(a)||Vb(a)?!1:"getUntrustedUpdateValue"in a};uo.prototype.getUntrustedUpdateValue=uo.prototype.Uh;var vo=[],wo=!1,xo=!1,yo=!1,zo=function(a){return g["dataLayer"].push(a)},Ao=function(a){var b=mf["dataLayer"],c=b?b.subscribers:1,d=0,e=a;return function(){++d===c&&(e(),e=null)}};
function Bo(a){var b=a._clear;Ha(a,function(d,e){"_clear"!==d&&(b&&If(d,void 0),If(d,e))});uf||(uf=a["gtm.start"]);var c=a["gtm.uniqueEventId"];if(!a.event)return!1;c||(c=zf(),a["gtm.uniqueEventId"]=c,If("gtm.uniqueEventId",c));return nk(a)}function Co(){var a=vo[0];if(null==a||"object"!==typeof a)return!1;if(a.event)return!0;if(Ka(a)){var b=a[0];if("config"===b||"event"===b||"js"===b)return!0}return!1}
function Do(){for(var a=!1;!yo&&0<vo.length;){var b=!1;b=!0;if(b&&!xo&&Co()){var c={};vo.unshift((c.event=
"gtm.init",c));xo=!0}var d=!1;d=!0;if(d&&!wo&&Co()){var e={};vo.unshift((e.event="gtm.init_consent",e));wo=!0}yo=!0;delete Cf.eventModel;Ef();var f=vo.shift();if(null!=f){var h=to(f);
if(h){var k=f;f=to(k)?k.getUntrustedUpdateValue():void 0;for(var l=["gtm.allowlist","gtm.blocklist","gtm.whitelist","gtm.blacklist","tagTypeBlacklist"],n=0;n<l.length;n++){var p=l[n],r=Ff(p,1);if(xa(r)||Vb(r))r=E(r);Df[p]=r}}try{if(ua(f))try{f.call(Gf)}catch(z){}else if(xa(f)){var t=f;if(va(t[0])){var q=t[0].split("."),v=q.pop(),u=t.slice(1),w=Ff(q.join("."),2);if(void 0!==w&&null!==w)try{w[v].apply(w,u)}catch(z){}}}else{if(Ka(f)){a:{var y=f;if(y.length&&va(y[0])){var x=Zn[y[0]];if(x&&(!h||!$n[y[0]])){f=
x(y);break a}}f=void 0}if(!f){yo=!1;continue}}a=Bo(f)||a}}finally{h&&Ef(!0)}}yo=!1}return!a}
function Eo(){var b=Do();try{ao(g["dataLayer"],lf.M)}catch(c){}return b}
var Go=function(){var a=xb("dataLayer",[]),b=xb("google_tag_manager",{});b=b["dataLayer"]=b["dataLayer"]||{};Ai(function(){b.gtmDom||(b.gtmDom=!0,a.push({event:"gtm.dom"}))});Gn(function(){b.gtmLoad||(b.gtmLoad=!0,a.push({event:"gtm.load"}))});b.subscribers=(b.subscribers||0)+1;var c=a.push;a.push=function(){var e;if(0<mf.SANDBOXED_JS_SEMAPHORE){e=[];for(var f=0;f<arguments.length;f++)e[f]=new uo(arguments[f])}else e=[].slice.call(arguments,0);var h=c.apply(a,e);vo.push.apply(vo,e);if(300<
this.length)for(td(4);300<this.length;)this.shift();var k="boolean"!==typeof h||h;return Do()&&k};var d=a.slice(0);vo.push.apply(vo,d);if(Fo()){C(Eo)}},Fo=function(){var a=!0;return a};var Ho={};Ho.Qc=new String("undefined");
var Io=function(a){this.o=function(b){for(var c=[],d=0;d<a.length;d++)c.push(a[d]===Ho.Qc?b:a[d]);return c.join("")}};Io.prototype.toString=function(){return this.o("undefined")};Io.prototype.valueOf=Io.prototype.toString;Ho.rh=Io;Ho.Xd={};Ho.Hh=function(a){return new Io(a)};var Jo={};Ho.xi=function(a,b){var c=zf();Jo[c]=[a,b];return c};Ho.Mf=function(a){var b=a?0:1;return function(c){var d=Jo[c];if(d&&"function"===typeof d[b])d[b]();Jo[c]=void 0}};Ho.ai=function(a){for(var b=!1,c=!1,d=2;d<a.length;d++)b=
b||8===a[d],c=c||16===a[d];return b&&c};Ho.oi=function(a){if(a===Ho.Qc)return a;var b=zf();Ho.Xd[b]=a;return'google_tag_manager["'+lf.M+'"].macro('+b+")"};Ho.ki=function(a,b,c){a instanceof Ho.rh&&(a=a.o(Ho.xi(b,c)),b=ta);return{Vh:a,onSuccess:b}};var Uo=g.clearTimeout,Vo=g.setTimeout,L=function(a,b,c){if(Sh()){b&&C(b)}else return Bb(a,b,c)},Wo=function(){return new Date},Xo=function(){return g.location.href},Yo=function(a){return ue(we(a),"fragment")},Zo=function(a){return ve(we(a))},$o=function(a,b){return Ff(a,b||2)},ap=function(a,b,c){var d;b?(a.eventCallback=b,c&&(a.eventTimeout=c),d=zo(a)):d=zo(a);return d},bp=function(a,b){g[a]=b},O=function(a,b,c){b&&
(void 0===g[a]||c&&!g[a])&&(g[a]=b);return g[a]},cp=function(a,b,c){return Xf(a,b,void 0===c?!0:!!c)},dp=function(a,b,c){return 0===fg(a,b,c)},ep=function(a,b){if(Sh()){b&&C(b)}else Db(a,b)},fp=function(a){return!!tn(a,"init",!1)},gp=function(a){rn(a,"init",!0)},hp=function(a){var b=sf+"?id="+encodeURIComponent(a)+"&l=dataLayer";L(Uh("https://","http://",b))},ip=function(a,b,c){Jj&&(Wb(a)||Xj(c,b,a))};var jp=Ho.ki;var Gp=encodeURI,T=encodeURIComponent,Hp=Eb;var Ip=function(a,b){if(!a)return!1;var c=ue(we(a),"host");if(!c)return!1;for(var d=0;b&&d<b.length;d++){var e=b[d]&&b[d].toLowerCase();if(e){var f=c.length-e.length;0<f&&"."!=e.charAt(0)&&(f--,e="."+e);if(0<=f&&c.indexOf(e,f)==f)return!0}}return!1};
var Jp=function(a,b,c){for(var d={},e=!1,f=0;a&&f<a.length;f++)a[f]&&a[f].hasOwnProperty(b)&&a[f].hasOwnProperty(c)&&(d[a[f][b]]=a[f][c],e=!0);return e?d:null};function pr(){return g.gaGlobal=g.gaGlobal||{}}var qr=function(){var a=pr();a.hid=a.hid||Aa();return a.hid},rr=function(a,b){var c=pr();if(void 0==c.vid||b&&!c.from_cookie)c.vid=a,c.from_cookie=b};var Sr=function(){if(ua(g.__uspapi)){var a="";try{g.__uspapi("getUSPData",1,function(b,c){if(c&&b){var d=b.uspString;d&&/^[\da-zA-Z-]{1,20}$/.test(d)&&(a=d)}})}catch(b){}return a}};var ms=window,ns=document,os=function(a){var b=ms._gaUserPrefs;if(b&&b.ioo&&b.ioo()||a&&!0===ms["ga-disable-"+a])return!0;try{var c=ms.external;if(c&&c._gaUserPrefs&&"oo"==c._gaUserPrefs)return!0}catch(f){}for(var d=Tf("AMP_TOKEN",String(ns.cookie),!0),e=0;e<d.length;e++)if("$OPT_OUT"==d[e])return!0;return ns.getElementById("__gaOptOutExtension")?!0:!1};var ps={};function ss(a){delete a.eventModel[H.Ub];us(a.eventModel)}
var us=function(a){Ha(a,function(c){"_"===c.charAt(0)&&delete a[c]});var b=a[H.Na]||{};Ha(b,function(c){"_"===c.charAt(0)&&delete b[c]})};var xs=function(a,b,c){en(b,c,a)},ys=function(a,b,c){en(b,c,a,!0)},Ds=function(a,b){};
function zs(a,b){}var W={g:{}};

W.g.e=["google"],function(){(function(a){W.__e=a;W.__e.h="e";W.__e.m=!0;W.__e.priorityOverride=0})(function(a){var b=String(Lf(a.vtp_gtmEventId,"event"));a.vtp_gtmCachedValues&&(b=String(a.vtp_gtmCachedValues.event));return b})}();
W.g.f=["google"],function(){(function(a){W.__f=a;W.__f.h="f";W.__f.m=!0;W.__f.priorityOverride=0})(function(a){var b=$o("gtm.referrer",1)||m.referrer;return b?a.vtp_component&&"URL"!=a.vtp_component?ue(we(String(b)),a.vtp_component,a.vtp_stripWww,a.vtp_defaultPages,a.vtp_queryKey):Zo(String(b)):String(b)})}();

W.g.u=["google"],function(){var a=function(b){return{toString:function(){return b}}};(function(b){W.__u=b;W.__u.h="u";W.__u.m=!0;W.__u.priorityOverride=0})(function(b){var c;c=(c=b.vtp_customUrlSource?b.vtp_customUrlSource:$o("gtm.url",1))||Xo();var d=b[a("vtp_component")];if(!d||"URL"==d)return Zo(String(c));var e=we(String(c)),f;if("QUERY"===d)a:{var h=b[a("vtp_multiQueryKeys").toString()],k=b[a("vtp_queryKey").toString()]||"",l=b[a("vtp_ignoreEmptyQueryParam").toString()],n;h?xa(k)?n=k:n=String(k).replace(/\s+/g,
"").split(","):n=[String(k)];for(var p=0;p<n.length;p++){var r=ue(e,"QUERY",void 0,void 0,n[p]);if(void 0!=r&&(!l||""!==r)){f=r;break a}}f=void 0}else f=ue(e,d,"HOST"==d?b[a("vtp_stripWww")]:void 0,"PATH"==d?b[a("vtp_defaultPages")]:void 0,void 0);return f})}();
W.g.ua=["google"],function(){function a(q){return K(q)}function b(q,v,u){var w=!1;if(Od()&&!w&&!f[q]){var y=!K(H.H),x=function(){var z=Ni(),A="gtm"+zf(),B=r(v);B["&gtm"]=Gk(!0);var D={name:A};p(B,D,!0);var F=void 0,G=D._useUp;z(function(){var J=z.getByName(u);J&&(F=J.get("clientId"))});
z("create",q,D);y&&K(H.H)&&(y=!1,z(function(){var J=z.getByName(A);!J||J.get("clientId")===F&&G||(B["&gcs"]=Yd(),B["&gcu"]="1",J.set(B),J.send("pageview"))}));z(function(){z.remove(A)})};Td(x,H.H);Td(x,H.D);f[q]=!0}}var c=!1;var d,e={},f={},h={name:!0,
clientId:!0,sampleRate:!0,siteSpeedSampleRate:!0,alwaysSendReferrer:!0,allowAnchor:!0,allowLinker:!0,cookieName:!0,cookieDomain:!0,cookieExpires:!0,cookiePath:!0,cookieUpdate:!0,cookieFlags:!0,legacyCookieDomain:!0,legacyHistoryImport:!0,storage:!0,useAmpClientId:!0,storeGac:!0,_cd2l:!0,_useUp:!0,_cs:!0},k={allowAnchor:!0,allowLinker:!0,alwaysSendReferrer:!0,anonymizeIp:!0,cookieUpdate:!0,exFatal:!0,forceSSL:!0,javaEnabled:!0,legacyHistoryImport:!0,nonInteraction:!0,useAmpClientId:!0,useBeacon:!0,
storeGac:!0,allowAdFeatures:!0,allowAdPersonalizationSignals:!0,_cd2l:!0},l={urlPassthrough:!0};var p=function(q,v,u){var w=0;if(q)for(var y in q)if(!l[y]&&q.hasOwnProperty(y)&&(u&&h[y]||!u&&void 0===h[y])){var x=k[y]?Ma(q[y]):q[y];"anonymizeIp"!=
y||x||(x=void 0);v[y]=x;w++}return w},r=function(q){var v={};q.vtp_gaSettings&&E(Jp(q.vtp_gaSettings.vtp_fieldsToSet,"fieldName","value"),v);E(Jp(q.vtp_fieldsToSet,"fieldName","value"),v);Ma(v.urlPassthrough)&&(v._useUp=!0);q.vtp_transportUrl&&(v._x_19=q.vtp_transportUrl);if(!c){
K(H.H)||(v.storage="none");K(H.D)||(v.allowAdFeatures=!1,v.storeGac=!1);ym()||(v.allowAdFeatures=!1);xm()||(v.allowAdPersonalizationSignals=!1);if(Ma(v.urlPassthrough)){var u=!1;Od()&&!u&&(v._cs=a)}}return v},t=function(q){function v(ma,X){void 0!==q[X]&&J("set",ma,q[X])}var u={},w={},y={},x={};if(q.vtp_gaSettings){var z=q.vtp_gaSettings;E(Jp(z.vtp_contentGroup,"index","group"),w);E(Jp(z.vtp_dimension,"index","dimension"),y);E(Jp(z.vtp_metric,"index","metric"),x);var A=E(z);A.vtp_fieldsToSet=void 0;A.vtp_contentGroup=void 0;A.vtp_dimension=
void 0;A.vtp_metric=void 0;q=E(q,A)}E(Jp(q.vtp_contentGroup,"index","group"),w);E(Jp(q.vtp_dimension,"index","dimension"),y);E(Jp(q.vtp_metric,"index","metric"),x);var B=r(q),D=Pi(q.vtp_functionName);if(ua(D)){var F="",G="";q.vtp_setTrackerName&&"string"==typeof q.vtp_trackerName?""!==q.vtp_trackerName&&(G=q.vtp_trackerName,F=G+"."):(G="gtm"+zf(),F=G+".");var J=function(ma){var X=[].slice.call(arguments,0);X[0]=F+X[0];D.apply(window,X)},N=function(ma,X){return void 0===X?X:ma(X)},S=function(ma,X){if(X)for(var Ta in X)X.hasOwnProperty(Ta)&&
(c?B[ma+Ta]=X[Ta]:J("set",ma+Ta,X[Ta]))},R=function(){},
P=function(ma,X){return void 0===q[ma]?u[X]:q[ma]},I=q.vtp_trackingId||u.trackingId;if(!c){var oa=function(ma,X){void 0!==X&&J("set",ma,X)},Ba={name:G};p(B,Ba,!0);D("create",I,Ba);J("set","&gtm",Gk(!0));S("contentGroup",w);S("dimension",y);S("metric",x);var Fa=!1;Od()&&!Fa&&(J("set","&gcs",Yd()),b(I,q,G));B._x_19&&B._x_20&&!e[G]&&(e[G]=!0,D(Ui(G,String(B._x_20))));q.vtp_enableRecaptcha&&J("require","recaptcha","recaptcha.js");v("nonInteraction","vtp_nonInteraction");var Wc={};p(B,Wc,!1)&&J("set",Wc);q.vtp_enableLinkId&&J("require","linkid","linkid.js");J("set","hitCallback",function(){var ma=B&&B.hitCallback;ua(ma)&&ma();q.vtp_gtmOnSuccess()})}var zb;if("TRACK_EVENT"==q.vtp_trackType){if(!c){}}else if("TRACK_SOCIAL"==q.vtp_trackType){if(!c){}}else if("TRACK_TRANSACTION"==q.vtp_trackType){}else if("TRACK_TIMING"==
q.vtp_trackType){if(!c){}}else if("DECORATE_LINK"==q.vtp_trackType){}else if("DECORATE_FORM"==q.vtp_trackType){}else if("TRACK_DATA"==q.vtp_trackType){}else if(!c){q.vtp_enableEcommerce&&(J("require","ec","ec.js"),R());if(q.vtp_doubleClick||"DISPLAY_FEATURES"==q.vtp_advertisingFeaturesType){var Vi=
"_dc_gtm_"+String(q.vtp_trackingId).replace(/[^A-Za-z0-9-]/g,"");J("require","displayfeatures",void 0,{cookieName:Vi})}if("DISPLAY_FEATURES_WITH_REMARKETING_LISTS"==q.vtp_advertisingFeaturesType){var Bd="_dc_gtm_"+String(q.vtp_trackingId).replace(/[^A-Za-z0-9-]/g,"");J("require","adfeatures",{cookieName:Bd})}zb?J("send","pageview",zb):J("send","pageview");Ma(B.urlPassthrough)&&Ri(F)}if(!d){var xc=q.vtp_useDebugVersion?"u/analytics_debug.js":"analytics.js";q.vtp_useInternalVersion&&!q.vtp_useDebugVersion&&(xc="internal/"+xc);d=!0;var Ee=pk(B._x_19,"/analytics.js"),Yc=Uh("https:","http:","//www.google-analytics.com/"+xc,B&&!!B.forceSSL);L("analytics.js"===xc&&Ee?Ee:Yc,function(){var ma=Ni();ma&&ma.loaded||q.vtp_gtmOnFailure();},
q.vtp_gtmOnFailure)}}else C(q.vtp_gtmOnFailure)};(function(q){W.__ua=q;W.__ua.h="ua";W.__ua.m=!0;W.__ua.priorityOverride=0})(function(q){$d(function(){t(q)},[H.H,H.D])})}();








W.g.gas=["google"],function(){(function(a){W.__gas=a;W.__gas.h="gas";W.__gas.m=!0;W.__gas.priorityOverride=0})(function(a){var b=E(a),c=b;c[Xb.kb]=null;c[Xb.jh]=null;var d=b=c;d.vtp_fieldsToSet=d.vtp_fieldsToSet||[];var e=d.vtp_cookieDomain;void 0!==e&&(d.vtp_fieldsToSet.push({fieldName:"cookieDomain",value:e}),delete d.vtp_cookieDomain);return b})}();
W.g.ga=["google"],function(){var a,b;(function(c){W.__ga=c;W.__ga.h="ga";W.__ga.m=!0;W.__ga.priorityOverride=0})(function(c){function d(P){var I=[].slice.call(arguments,0);I[0]=v+I[0];t.push(I)}function e(P,I){void 0!==c[I]&&d(P,c[I])}function f(P,I){void 0!==c[I]&&d(P,Number(c[I]))}function h(P,I){if(r(I))for(var Q=0;Q<I.length;Q++)d(P,I[Q])}function k(P,I,Q){if(r(I))for(var U=0;U<I.length;U++){for(var M=[P],Y=I[U],ka=0;ka<Q.length;ka++)M.push(Y[Q[ka]]);
d.apply(this,M)}}function l(P,I){void 0!==c[I]&&d("_set",P,c[I])}function n(P,I){return void 0===I?I:P(I)}function p(P,I){void 0!==I&&(u+="&"+P+"="+I)}var r=xa,t=O("_gaq",[],!1),q=!1,v="";void 0==c.vtp_trackerName?v="gtm"+zf()+".":""!==c.vtp_trackerName&&(v=c.vtp_trackerName+".");e("_setAccount","vtp_webPropertyId");d("_set","gtmid",Gk(!0));
e("_setAllowLinker","vtp_allowLinker");
e("_setAllowAnchor","vtp_allowAnchor");e("_setAllowHash","vtp_allowHash");
h("_addIgnoredRef",c.vtp_ignoredRef);h("_addIgnoredOrganic",c.vtp_ignoredOrganic);var u="";if(""!==u){var w=function(P,I,Q){for(var U=I.length-1;0<=U;U--){var M=I[U].split("=");if(M[0]===P)return M[1]||"1"}for(var Y=Q.length-1;0<=Y;Y--){var ka=Q[Y].split("=");if(ka[0]===P)return ka[1]||"1"}},y=we(Xo()),x=ue(y,"query").split("&"),z=c.vtp_allowAnchor?ue(y,"fragment").split("&"):[];p("gclid",w("gclid",z,x));p("gclsrc",w("gclsrc",z,x));p("dclid",w("dclid",z,x));d("_set","campaignParams",
u)}l("anonymizeIp","vtp_anonymizeIp");c.vtp_enableInPageLinkId&&d("_require","inpage_linkid","//www.google-analytics.com/plugins/ga/inpage_linkid.js");e("_setCampaignTrack","vtp_campaignTrack");e("_setClientInfo","vtp_clientInfo");e("_setDetectFlash","vtp_detectFlash");
e("_setDetectTitle","vtp_detectTitle");void 0!==c.vtp_forceSsl&&c.vtp_forceSsl&&(t.push(["_gat._forceSSL"]),q=!!c.vtp_forceSsl);
d("_set","hitCallback",function(){ua(c.vtp_hitCallback)&&c.vtp_hitCallback();c.vtp_gtmOnSuccess()});if("TRACK_EVENT"==c.vtp_trackType){}else if("TRACK_TRANSACTION"==c.vtp_trackType){}else if("LINK"==c.vtp_trackType){}else if("LINK_BY_POST"==c.vtp_trackType){}else if("TRACK_SOCIAL"==c.vtp_trackType){}else if("TRACK_TIMING"==c.vtp_trackType){}else if("DECORATE_LINK"==c.vtp_trackType){}else if("DECORATE_FORM"==c.vtp_trackType){}else d("_trackPageview");
h("_cookiePathCopy",c.vtp_cookiePathCopy);var S=function(){O("_gat")||c.vtp_gtmOnFailure()};if(c.vtp_doubleClick)b||(b=!0,L(Uh("https","http","://stats.g.doubleclick.net/dc.js",q),S,c.vtp_gtmOnFailure));else if(!a){var R=c.vtp_useDebugVersion?".google-analytics.com/u/ga_debug.js":".google-analytics.com/ga.js";a=!0;L(Uh("https://ssl","http://www",R,q),S,c.vtp_gtmOnFailure)}})}();
W.g.hl=["google"],function(){function a(f){return f.target&&f.target.location&&f.target.location.href?f.target.location.href:Xo()}function b(f,h){Fb(f,"hashchange",function(k){var l=a(k);h({source:"hashchange",state:null,url:Zo(l),ba:Yo(l)})})}function c(f,h){Fb(f,"popstate",function(k){var l=a(k);h({source:"popstate",state:k.state,url:Zo(l),ba:Yo(l)})})}function d(f,h,k){var l=h.history,n=l[f];if(ua(n))try{l[f]=function(p,r,t){n.apply(l,[].slice.call(arguments,0));k({source:f,state:p,url:Zo(Xo()),
ba:Yo(Xo())})}}catch(p){}}function e(){var f={source:null,state:O("history").state||null,url:Zo(Xo()),ba:Yo(Xo())};return function(h){var k=f,l={};l[k.source]=!0;l[h.source]=!0;if(!l.popstate||!l.hashchange||k.ba!=h.ba){var n={event:"gtm.historyChange","gtm.historyChangeSource":h.source,"gtm.oldUrlFragment":f.ba,"gtm.newUrlFragment":h.ba,"gtm.oldHistoryState":f.state,"gtm.newHistoryState":h.state,"gtm.oldUrl":f.url,"gtm.newUrl":h.url};f=h;ap(n)}}}(function(f){W.__hl=f;W.__hl.h="hl";W.__hl.m=!0;W.__hl.priorityOverride=
0})(function(f){var h=O("self");if(!fp("hl")){var k=e();b(h,k);c(h,k);d("pushState",h,k);d("replaceState",h,k);gp("hl")}C(f.vtp_gtmOnSuccess)})}();















var Es={};Es.macro=function(a){if(Ho.Xd.hasOwnProperty(a))return Ho.Xd[a]},Es.onHtmlSuccess=Ho.Mf(!0),Es.onHtmlFailure=Ho.Mf(!1);Es.dataLayer=Gf;Es.callback=function(a){xf.hasOwnProperty(a)&&ua(xf[a])&&xf[a]();delete xf[a]};Es.bootstrap=0;Es._spx=!1;function Fs(){mf[lf.M]=Es;Wa(yf,W.g);Hc=Hc||Ho;Ic=Qc}
function Gs(){var a=!1;a&&Ji("INIT");yd().s();mf=g.google_tag_manager=g.google_tag_manager||{};il();
dh.enable_gbraid_cookie_write=!0;if(mf[lf.M]){var b=mf.zones;b&&b.unregisterChild(lf.M);}else{for(var c=data.resource||{},d=c.macros||[],e=0;e<d.length;e++)vc.push(d[e]);for(var f=c.tags||[],h=0;h<f.length;h++)Dc.push(f[h]);for(var k=c.predicates||[],l=0;l<k.length;l++)Cc.push(k[l]);for(var n=c.rules||[],p=0;p<n.length;p++){for(var r=n[p],t={},q=
0;q<r.length;q++)t[r[q][0]]=Array.prototype.slice.call(r[q],1);Bc.push(t)}Fc=W;Gc=Nn;Fs();Go();vi=!1;wi=0;if("interactive"==m.readyState&&!m.createEventObject||"complete"==m.readyState)yi();else{Fb(m,"DOMContentLoaded",yi);Fb(m,"readystatechange",yi);if(m.createEventObject&&m.documentElement.doScroll){var v=!0;try{v=!g.frameElement}catch(z){}v&&zi()}Fb(g,"load",yi)}Dn=!1;"complete"===m.readyState?Fn():Fb(g,"load",Fn);Jj&&g.setInterval(Dj,864E5);vf=(new Date).getTime();if(a){var x=Ki("INIT");}}}
(function(a){if(!g["__TAGGY_INSTALLED"]){var b=!1;if(m.referrer){var c=we(m.referrer);b="cct.google"===te(c,"host")}if(!b){var d=Xf("googTaggyReferrer");b=d.length&&d[0].length}b&&(g["__TAGGY_INSTALLED"]=!0,Bb("https://cct.google/taggy/agent.js"))}var f=function(){var n=g["google.tagmanager.debugui2.queue"];n||(n=[],g["google.tagmanager.debugui2.queue"]=n,Bb("https://www.googletagmanager.com/debug/bootstrap"));var p={messageType:"CONTAINER_STARTING",data:{scriptSource:wb,containerProduct:"GTM",debug:!1}};p.data.resume=function(){a()};lf.zg&&(p.data.initialPublish=!0);n.push(p)},h="x"===ue(g.location,"query",!1,void 0,"gtm_debug");if(!h&&m.referrer){var k=we(m.referrer);h="tagassistant.google.com"===te(k,"host")}if(!h){var l=Xf("__TAG_ASSISTANT");h=l.length&&l[0].length}g.__TAG_ASSISTANT_API&&(h=!0);h&&wb?f():a()})(Gs);

})()
